### ISSUE TITLE
Не загружается компонент на HA 2022.8.0

### ISSUE THREAD

**Issue by ffrants** [TionAPI/HA-tion#102]
## Общая информация
  * **версия Home Assistant**: 2022.8.0
  * **способ установки Home Assistant**:
    [ ] venv
    [ ] Docker
    [ х ] Home Assistant OS
 * **версия компонента**: 3.0.2
 * **Модель бризера**: 
 * **версия python-модуля**: 
 [ X ] в момент проявления проблемы к бризеру никто не подключен
 [ X ] bluetooth в системе работает корректно, действий из (WiKi)[https://github.com/TionAPI/HA-tion/wiki/Bluetooth] не требуется
 [ X ] проблема не похожа ни на одну из (FAQ)[https://github.com/TionAPI/HA-tion/wiki/FAQ]
## Краткое описание 
Интеграция не загружается 

## Debug-log
```

Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 22:42:58 (3 occurrences) 
Last logged: 22:43:01

Unable to install package tion-btle==2.0.6: ERROR: Cannot install tion-btle==2.0.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts


Logger: homeassistant.setup
Source: setup.py:184 
First occurred: 22:43:01 (1 occurrences) 
Last logged: 22:43:01

Setup failed for custom integration tion: Requirements for tion not found: ['tion-btle==2.0.6'].

```

## Как можно воспроизвети вашу проблему
Обновить HA до версии 2022.8.0, перезапустить HA

**Comment by IATkachenko** [comment]
Видимо, они подняли версию `bleak`.

**Comment by IATkachenko** [comment]
Можете прописать в `manifest.json` интеграции:
```json
  "requirements": [
    "tion-btle==3.0.0"
  ],
```
(там сейчас `2.0.6`)
Фикс в виде релиза будет как сам руками все потрогаю.

**Comment by ffrants** [comment]
Спасибо, ошибка пропала

**Comment by IATkachenko** [comment]
Исправлено в [v3.0.3](https://github.com/TionAPI/HA-tion/releases/tag/v3.0.3)
