### ISSUE TITLE
Конфликт с облачной интеграцией

### ISSUE THREAD

**Issue by aatemes** [TionAPI/HA-tion#108]
## Общая информация
  * **версия Home Assistant**: 2022.8.4
  * **способ установки Home Assistant**:
    [Х] venv
    [ ] Docker
    [ ] Home Assistant OS
 * **версия компонента**: не ставится
 * **модель бризера**: S3 
 * **версия python-модуля**: 3.9

[х] в момент проявления проблемы к бризеру никто не подключен
[х] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[х] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
Не могу поставить компонент - предположительно, из-за конфликта с https://github.com/airens/tion_home_assistant 

## Debug-log
не применимо

## Как можно воспроизвести вашу проблему
1. Поставить компонент от airens (он ставится в config/custom_components/tion)
2. Попробовать через HACS поставить компонент [HA-tion](https://github.com/TionAPI/HA-tion) - судя по всему, он пишется в ту же директорию, затирая предыдущий компонент. 

## Дополнительное описание
Добрый день! 
Сейчас у меня бризеры и тионовские датчики прокинуты в HA через облачную интеграцию от airens. Всё работает, но:
1. Пару раз у Тиона отваливался личный кабинет (один раз они сертификаты просрочили, второй раз просто серверы несколько часов не отвечали).  Как назло, оба раза бризеры жарили на максимальной скорости,  а надо было их перед сном утихомирить. В первый раз пришлось искать пульты и вставлять в них батарейки. Во второй раз вспомнил про приложение Tion Remote на телефоне:) 
2. Не очень правильно, что нет локального управления. 

Хотелось бы иметь возможность управлять бризерами локально через HA. Но не лишаясь данных по CO2 и прочему с MagicAir'а и датчика CO2. 
Предположительно, оба компонента пишутся в одну директорию и создают объекты в одном домене, из-за чего тот, что ставится вторым, не появляется в списке доступных интеграций в HA. 
Попробовал руками закинуть файлики в custom_components/tion_btle - не помогло. Подумал, что из-за того, что домен в манифесте одинаковый... 
Поправил домен в манифесте - написал tion_btle вместо tion. Частично помогло - интеграция появилась в списке по кнопке "Добавить интеграцию" в HA, но при попытке её установить - ошибка HA: 
_Эта интеграция не поддерживает настройку через пользовательский интерфейс. Если Вы перешли по этой ссылке с веб-сайта Home Assistant, убедитесь, что у Вас установлена последняя версия Home Assistant._
Наверное, что-то ещё конфликтует... 
Подскажите, что ещё нужно поправить, чтобы одновременно работали 2 интеграции? Понимаю, что ситуация наверное специфическая, и менять домен во всем компоненте не стоит (затронет всех пользователей), поэтому готов сделать это ручками - только подскажите, что:)

**Comment by IATkachenko** [comment]
Домены в HA используется разные (не смотря на то что в манифесте -- одинаковые), а вот структура модулей у нас, действительно, конфиликтует.
Это все происходит на уровне пакетов python.
Выглядит это так:
```python
from foo import bar
```
Означает что python попытается в custrom_components/**foo** найти файл `__init.py__` и из него импортировать `bar`.
Те если изменен путь к компоненту в cutom_components, это означает что должны быть соответствующий образом обновлены все импотры в коде.

Интеграция `airens` появилась раньше, да и у нас из-за проблем с компонентом `bluetooth` не самые лучшие времена. Так что интеграцию подвину в другой каталог в ближайшее время, чтобы не было конфликтов.

**Comment by IATkachenko** [comment]
Исправлено в [v4.0.0](https://github.com/TionAPI/HA-tion/releases/tag/v4.0.0).
