### ISSUE TITLE
async_setup_platforms скоро перестанет работать

### ISSUE THREAD

**Issue by tms320** [TionAPI/HA-tion#122]
## Общая информация
  * **версия Home Assistant**: 2023.3.6
  * **способ установки Home Assistant**: Home Assistant Supervised
 * **версия компонента**: v4.1.4
 * **модель бризера**: S4

## Краткое описание 
В логе HA увидел такое сообщение:  

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 23 марта 2023 г., 22:02:08 (2 occurrences)
Last logged: 26 марта 2023 г., 11:20:09
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for ha_tion_btle using this method at custom_components/ha_tion_btle/__init__.py, line 45: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)

**Comment by IATkachenko** [comment]
Исправлено в [v4.1.5](https://github.com/TionAPI/HA-tion/releases/tag/v4.1.5).
