### ISSUE TITLE
Невозможно создать пару с бризером Lite

### ISSUE THREAD

**Issue by Yiivgeny** [TionAPI/HA-tion#132]
## Общая информация
  * **версия Home Assistant**: 2024.7.4
  * **способ установки Home Assistant**: 
    [ ] venv
    [ ] Docker
    [x] Home Assistant OS
 * **версия компонента**: 4.1.8
 * **Модель бризера**:  Lite
 * **версия python-модуля**: 
 [x] в момент проявления проблемы к бризеру никто не подключен
 [x] bluetooth в системе работает корректно, действий из (WiKi)[https://github.com/TionAPI/HA-tion/wiki/Bluetooth] не требуется
 [x] проблема не похожа ни на одну из (FAQ)[https://github.com/TionAPI/HA-tion/wiki/FAQ]
## Краткое описание 
Невозможно создать пару с бризером Lite

## Debug-log
```
Cannot pair and get data. Data is {'model': 'Lite', 'name': 'Tion Breezer', 'mac': 'C9:7F:99:C2:48:3E', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; 
RuntimeError: Caught blocking call to sleep with args (3,) inside the event loop by custom integration 'ha_tion_btle' at custom_components/ha_tion_btle/config_flow.py, line 168: time.sleep(3). (offender: /config/custom_components/ha_tion_btle/config_flow.py, line 168: time.sleep(3)), please report it to the author of the 'ha_tion_btle' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
```

## Как можно воспроизвети вашу проблему
При первичном подключение всё заканчивается сообщением "Can't pair"

**Comment by IATkachenko** [comment]
@Yiivgeny, привет.

Выглядит так что к бризеру мы подключились, данные прочитали: оно так [на любой exception](https://github.com/TionAPI/HA-tion/blob/deb81d9fefa02d69e3468a88167df7f38726cc58/custom_components/ha_tion_btle/config_flow.py#L171) во время сопряжения реагирует.
Попробуйте теперь добавить интеграцию без сопряжения. Должно сработать.
Если нет -- нужно копать в сторону проблем с сопряжением, в первую очередь. https://github.com/TionAPI/HA-tion/wiki/Bluetooth может помочь.

**Comment by Yiivgeny** [comment]
Перешел на https://github.com/dentra/esphome-tion
Работает идеально, функций намного больше
