### ISSUE TITLE
Requesting to add Tion Bio X SM (uses tuya wifi module)

### ISSUE THREAD

**Issue by porok** [TionAPI/HA-tion#136]
Прошу рассмотреть возможность добавления в интеграцию новых моделей с модулями Tuya Wifi.
Tion Bio X SM Base
Tion Bio X SM Standard
https://tion.ru/shop/tion-breezer-bio-x-smstandart/

**Comment by IATkachenko** [comment]
Тую проще подключать через родные для Туи интеграции -- https://github.com/make-all/tuya-local подойдет лучше всего.

Идея этой интеграции была в том чтобы подружить бризеры у которых на борту только BT.

**Comment by porok** [comment]
Жаль, а то в туе его не видно, видно в приложении тион, но оно один в один туя.. и точно модуль туи стоит, они сами на сайте пишут. А так как оно не в туевском приложении, не могу её выловить через тую-локал

**Comment by IATkachenko** [comment]
> Жаль, а то в туе его не видно, видно в приложении тион, но оно один в один туя.. и точно модуль туи стоит, они сами на сайте пишут. А так как оно не в туевском приложении, не могу её выловить через тую-локал

А родная Туявская приложенька его видит? Обычно у устройств на ее основе с родной приложенькой совместимость сохраняется.
