### ISSUE TITLE
Поддержка нового бризера Tion Bio X

### ISSUE THREAD

**Issue by 3raider** [TionAPI/HA-tion#138]
Здравствуйте!Не планируется ли поддержка новой модели бризера Tion Bio X,у которого есть на борту Bluetooth (для связи с пультом управления) и Wi-Fi (модуль Tuya)

**Comment by IATkachenko** [comment]
в соседнем #136 обсуждали. То у чего есть совой WiFi модуль затаскивать по BT довольно неудобное занятие.
Правда там говорят что Туя странная и через localtuya не работает...
