### ISSUE TITLE
Интеграция с Tion Lite работает?

### ISSUE THREAD

**Issue by NKamaev** [TionAPI/HA-tion#14]
На официальном сайте в разделе комплектация указано, что есть "Управление через мобильное приложение Tion Remote"

**Comment by IATkachenko** [comment]
Этот репозиторий не имеет никакого отношения к официалам.
Это -- полностью hand made компонент для Home Assistant. И если вы его используете -- вы делаете это на свой страх и риск.

Lite версия пока не поддерживается. Работа в этом направлении велась, но в какой-то момент застопорилась.
Поддержка Lite версии в компоненте появится только после того как python-модуль, который отвечает за взаимодействие с бризером, научится с ним работать. За прогрессом в этом направлении можно следить в этом [репозитории](https://github.com/TionAPI/tion_python), а конкретнее -- в [этом issue](https://github.com/TionAPI/tion_python/issues/2)

**Comment by IATkachenko** [comment]
Модуль готов. Работы с компонентом переходят в активную фазу.
