### ISSUE TITLE
Минимальная и максимальная температура

### ISSUE THREAD

**Issue by Flaxing** [TionAPI/HA-tion#15]
Прошу добавить выделенные строки
![image](https://user-images.githubusercontent.com/11350953/94362858-90120200-00d7-11eb-8fd3-371ee058b11b.png)

    @property
    def min_temp(self):
        """Return the minimum temperature."""
        return 0

    @property
    def max_temp(self):
        """Return the maximum temperature."""
        return 30

Это позволит управлять температурой правильно - от 0 до 30 градусов:
![image](https://user-images.githubusercontent.com/11350953/94362955-1fb7b080-00d8-11eb-820a-36906d6ae222.png)

**Comment by IATkachenko** [comment]
PR залили бы сразу, раз правки уже есть ;)
В ближайшем релизе сделаю.
