### ISSUE TITLE
Заголовки статуса

### ISSUE THREAD

**Issue by fishenebelny** [TionAPI/HA-tion#16]
Предлагаю вместо "Выключено"  писать "Выкл.".
На телефоне если смотреть текст за границу уходит. Ну и лаконичнее будет, как мне кажется.

**Comment by fishenebelny** [comment]
Могу попробовать и код тут поправить, но я чкстно не знаю как этотправильно делать.

**Comment by IATkachenko** [comment]
Текстовые значения состояний идут из Home Assistant и с компонентом не связаны вообще никак.
Компонент отдает состояние в виде внутреннего идентификатора, который потом интерпретирует HA.
