### ISSUE TITLE
В чём отличие?

### ISSUE THREAD

**Issue by allmoney** [TionAPI/HA-tion#21]
Добрый день!

Только что обнаружил что есть ещё одна, BT версия, компонента
https://github.com/TionAPI/HA-tion
https://github.com/airens/tion_home_assistant

Теперь в раздумьях, в чём + и - их? Какой предпочесть?

**Comment by IATkachenko** [comment]
@allmoney, добрый день.

Как сказано в [README](https://github.com/TionAPI/HA-tion/blob/master/README.md):
```
This custom integration will allow your Home assistant to control ... of your Tion S3 breezer via bluetooth. 
If you are prefer control breezer via Magic Air, please follow to https://github.com/airens/tion_home_assistant repository.
```
Те этот компонент общается с бризером напрямую, через bluetooth (и, соответственно, требует BTLE на том устройстве где запущен), а компонент от airens'a через HTTP при помощи MagicAir (и, соответственно, ему нужно чтобы у вас был тот самый MagicAir).

Какой предпочесть -- вам решать.
