### ISSUE TITLE
Не обновляется/изменяется статус сопряженного устройства tion lite

### ISSUE THREAD

**Issue by stsergo** [TionAPI/HA-tion#28]
В прололжение #27 
Модель: Lite, прошивка 054B
Интеграция: 1.4.2
tion-btle: 1.1.1
Все возможные bluetooth помехи отключены.

В логах следующее:
```
2020-12-16 00:05:35 INFO (MainThread) [custom_components.tion] Setting up None
2020-12-16 00:05:35 DEBUG (MainThread) [custom_components.tion] Tion instance updated at None
2020-12-16 00:05:35 DEBUG (MainThread) [custom_components.tion] Update fired force = True. Keep connection is False
2020-12-16 00:05:36 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
2020-12-16 00:05:38 CRITICAL (MainThread) [custom_components.tion] Got exception Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random
2020-12-16 00:05:38 CRITICAL (MainThread) [custom_components.tion] Will delay next check
2020-12-16 00:05:38 INFO (MainThread) [custom_components.tion.sensor] Init of sensor input temperature for 1fc0c7352e97048f183636b65ecf11dd (Tion Livingroom)
2020-12-16 00:05:38 INFO (MainThread) [custom_components.tion.sensor] Init of sensor filters remain for 1fc0c7352e97048f183636b65ecf11dd (Tion Livingroom)
2020-12-16 00:06:35 DEBUG (MainThread) [custom_components.tion] Tion instance updated at 2020-12-15 21:06:35.583404+00:00
2020-12-16 00:06:35 DEBUG (MainThread) [custom_components.tion] Update fired force = False. Keep connection is False
2020-12-16 00:06:35 DEBUG (MainThread) [custom_components.tion] Now is 2020-12-15 21:06:35.583404+00:00
2020-12-16 00:06:36 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
2020-12-16 00:06:38 CRITICAL (MainThread) [custom_components.tion] Got exception Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random
2020-12-16 00:06:38 CRITICAL (MainThread) [custom_components.tion] Will delay next check
2020-12-16 00:07:35 DEBUG (MainThread) [custom_components.tion] Tion instance updated at 2020-12-15 21:07:35.584456+00:00
2020-12-16 00:07:35 DEBUG (MainThread) [custom_components.tion] Update fired force = False. Keep connection is False
2020-12-16 00:07:35 DEBUG (MainThread) [custom_components.tion] Now is 2020-12-15 21:07:35.584456+00:00
```

При попытке изменить что-то из HA:
```
2020-12-16 00:18:25 INFO (MainThread) [custom_components.tion] Need to set: fan_speed=3, state='on'
2020-12-16 00:18:25 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception


2020-12-16 00:18:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139946349630320] Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random
    future.result()  # pop exception if have
  File "/home/hass/.homeassistant/custom_components/tion/climate.py", line 347, in async_set_fan_mode
  File "/home/hass/.homeassistant/custom_components/tion/climate.py", line 403, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/home/hass/.homeassistant/custom_components/tion/__init__.py", line 203, in set
    self.__tion.set(kwargs)
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 247, in set
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 311, in _connect
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 300, in _connect
```

Попробовал без HA позабирать данные в цикле. Перевожу бризер в режим сопряжения. Сопрягаю, потом пытаюсь забрать с помощью lite.py данные:
```
$ python3.8 1.py CB:86:F2:3F:3A:CB  2>&1|grep -e 'INFO' -e 'WARN';
sleep 3; echo; echo 'paired'; echo; 
while true; do 
  python3.8 lite.py CB:86:F2:3F:3A:CB 2>&1|grep -e 'INFO' -e 'WARN';
  sleep 5;
 done
INFO:__main__:Initial state: device is off, light is on, sound is on, heater is on, fan_speed is 3, target_temp is 20

paired

INFO:__main__:Initial state: device is off, light is on, sound is on, heater is on, fan_speed is 3, target_temp is 20
INFO:__main__:Initial state: device is off, light is on, sound is on, heater is on, fan_speed is 3, target_temp is 20
INFO:__main__:Initial state: device is off, light is on, sound is on, heater is on, fan_speed is 3, target_temp is 20
WARNING:tion_btle.tion:Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
WARNING:tion_btle.tion:Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
```
Т.е. похоже бризер все-таки не до конца сопрягается.

**Comment by IATkachenko** [comment]
Первые четыре раза вы данные успешно получаете.
Дальше бризер выходит из режима сопряжения по timeout'у?

**Comment by stsergo** [comment]
Да, первые 4 раза удачно, далее бризер вышел из режима сопряжения по таймауту. 
Я пробовал и с 30 и с 60 секундами - поведение одинаковое. Пока в режиме сопряжения - данные забираются, потом "Failed to connect"

bluetoothctl попробую, 
debug также приложу, заново только прогоню процесс с разными временами. Постараюсь сегодня прислать.

**Comment by IATkachenko** [comment]
Если 4 попытка после выхода из режима сопряжения -- timeout ни при чем.

**Comment by stsergo** [comment]
Вот эти попытки после выхода из режима сопряжения:
```
WARNING:tion_btle.tion:Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
WARNING:tion_btle.tion:Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
```

**Comment by IATkachenko** [comment]
Да, я понимаю общую картину. 
Во время тестов летом/осенью мы делали pairing через bluetoothctl и дополнительных манипуляций не делали. bluepy, как я понимаю, делает аналогичный pairing, поэтому и интересен вариант с pairing'ом через bluetoothctl.
А в плане timeout'ов единственное что имеет смысл проверять что все происходит по timeout, а не например из-за 3 неправильных пакетов. Но, судя по поведению, это имеенyо timeout pairing-режима.

**Comment by IATkachenko** [comment]
Мне сейчас очень интересно что именно вам говорят на стадии pair.
По идее, должно быть already paired. Но, судя по происходящему ниже, каждый раз говорят success.

**Comment by stsergo** [comment]
Прогнал ещё раз тесты. 

1. программкой и скриптом как вчера. с паузами 15 и 30 секунд. Лог с дебаг во вложении;
2. pair через bluetoothctl:
```
[bluetooth]# info CB:86:F2:3F:3A:CB
Device CB:86:F2:3F:3A:CB
	Name: Br Lite
	Alias: Br Lite
	Appearance: 0x0180
	Paired: no
	Trusted: no
	Blocked: no
	Connected: no
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (98f00001-3788-83ea-453e-f52244709ddb)
[bluetooth]# pair CB:86:F2:3F:3A:CB
Attempting to pair with CB:86:F2:3F:3A:CB
[CHG] Device CB:86:F2:3F:3A:CB Connected: yes
[NEW] Primary Service
	/org/bluez/hci0/dev_CB_86_F2_3F_3A_CB/service000a
	00001801-0000-1000-8000-00805f9b34fb
	Generic Attribute Profile
[NEW] Characteristic
	/org/bluez/hci0/dev_CB_86_F2_3F_3A_CB/service000a/char000b
	00002a05-0000-1000-8000-00805f9b34fb
	Service Changed
[NEW] Descriptor
	/org/bluez/hci0/dev_CB_86_F2_3F_3A_CB/service000a/char000b/desc000d
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[NEW] Primary Service
	/org/bluez/hci0/dev_CB_86_F2_3F_3A_CB/service000e
	98f00001-3788-83ea-453e-f52244709ddb
	Vendor specific
[NEW] Characteristic
	/org/bluez/hci0/dev_CB_86_F2_3F_3A_CB/service000e/char000f
	98f00002-3788-83ea-453e-f52244709ddb
	Vendor specific
[NEW] Characteristic
	/org/bluez/hci0/dev_CB_86_F2_3F_3A_CB/service000e/char0011
	98f00003-3788-83ea-453e-f52244709ddb
	Vendor specific
[NEW] Descriptor
	/org/bluez/hci0/dev_CB_86_F2_3F_3A_CB/service000e/char0011/desc0013
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[CHG] Device CB:86:F2:3F:3A:CB ServicesResolved: yes
[CHG] Device CB:86:F2:3F:3A:CB Paired: yes
Pairing successful
[Br Lite]# info CB:86:F2:3F:3A:CB
Device CB:86:F2:3F:3A:CB
	Name: Br Lite
	Alias: Br Lite
	Appearance: 0x0180
	Paired: yes
	Trusted: no
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (98f00001-3788-83ea-453e-f52244709ddb)
[CHG] Device CB:86:F2:3F:3A:CB ServicesResolved: no
[CHG] Device CB:86:F2:3F:3A:CB Connected: no
[bluetooth]# exit
```
попытался после этого забрать данные:
```
# Wed Dec 16 13:59:31 MSK 2020 python3.8 lite.py CB:86:F2:3F:3A:CB
WARNING:tion_btle.tion:Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
Traceback (most recent call last):
  File "lite.py", line 18, in <module>
    result = device.get()
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 217, in get
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 311, in _connect
    raise e
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 300, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random
^C
```

Попытка connect и pair через bluetoothctl: 
```
[bluetooth]# pair CB:86:F2:3F:3A:CB
Attempting to pair with CB:86:F2:3F:3A:CB
[CHG] Device CB:86:F2:3F:3A:CB Connected: yes
Failed to pair: org.bluez.Error.AuthenticationFailed
[CHG] Device CB:86:F2:3F:3A:CB Connected: no
[bluetooth]# connect CB:86:F2:3F:3A:CB
Attempting to connect to CB:86:F2:3F:3A:CB
[CHG] Device CB:86:F2:3F:3A:CB Connected: yes
Failed to connect: org.bluez.Error.Failed
[CHG] Device CB:86:F2:3F:3A:CB Connected: no
[log.txt](https://github.com/TionAPI/HA-tion/files/5702163/log.txt)

```

**Comment by IATkachenko** [comment]
Я что-то совсем не понимаю последний лог.
В первом логе вам сказали что
```
[CHG] Device CB:86:F2:3F:3A:CB Paired: yes
Pairing successful
```
А в последнем вы получаете
```
[CHG] Device CB:86:F2:3F:3A:CB Connected: yes
Failed to pair: org.bluez.Error.AuthenticationFailed
```
И дальше проходит connect, но тут же случается disconnect.

В 1.py я не вижу следов pair-команды (как я понимаю, pair() вы вызываете именно там, а дальше гоняете lite.py из репозитория модуля).

Пока очень похоже что бризер хочет pair-пакет, по аналогии с S3...

**Comment by stsergo** [comment]
Пардон, вчера вечером закоментировал pair в 1.py и забыл поправить (
Прогнал ещё раз. [log.txt](https://github.com/TionAPI/HA-tion/files/5702281/log.txt)

По bluetoothctl - в первом случае - бризер в режиме сопряжения, во втором - уже нет. 

Может стоит попробовать сопряжение на телефоне и снять лог/дамп?

**Comment by IATkachenko** [comment]
> Может стоит попробовать сопряжение на телефоне и снять лог/дамп?

Если есть такая возможность -- это было бы замечательно!

**Comment by stsergo** [comment]
Записал следующее:
- Сопряжение
- Включение бризера
- Изменение скорости с 3 до 2
- Изменение температуры с 20 до 19 градусов

Как вам лог передать? айфон пишет многовато для того, чтобы файл сюда прикладывать)

**Comment by IATkachenko** [comment]
Спасибо.
Любой файлобменник подойдет.

**Comment by stsergo** [comment]
Выложил [тынц](https://jk-hor.ru/Rx8TY5diuc9xW7/bluetoothd-hci-latest.pklg.zip)

По времени - с ~15:23 по 15:24

**Comment by IATkachenko** [comment]
Поймал. Еще раз спасибо!

**Comment by IATkachenko** [comment]
К сожалению, я не вижу ничего что указывало бы на какую-то специальную pair-процедуру (если разбить обмен на фразы как вы говорили, в сами пакеты внимательно не заглядывал):
 * 56923 - REQUEST_PARAMS
 * 57715 - REQUEST_DEVICE_INFO
### Включение бризера
 * REQUEST_PARAMS
 * SET_PARAMS
### Изменение скорости 
 * REQUEST_PARAMS
 * REQUEST_DEVICE_INFO (это, видимо, происходит по таймауту в фоне)
 * SET_PARAMS
 * REQUEST_PARAMS
 * REQUEST_PARAMS
### Изменение температуры
 * REQUEST_PARAMS
 * SET_PARAMS
 * REQUEST_PARAMS

В случае S3 есть отдельный WRITE для pair-команды.

Можно попробовать REQUEST_DEVICE_INFO повторить. Может в этом дело... Но летом, во время написания Lite-части, это точно не делалось.

**Comment by IATkachenko** [comment]
Покажите, пожалуйста, вот этот файлик:
```
cat  cat /var/lib/bluetooth/*/CB\:86\:F2\:3F\:3A\:CB/info
```
(там должны быть ключи, которые используются для общения и немного информации об устройстве)

**Comment by stsergo** [comment]
info:
```
[General]
Name=Br Lite
AddressType=static
SupportedTechnologies=LE;
Trusted=false
Blocked=false
Services=00001800-0000-1000-8000-00805f9b34fb;00001801-0000-1000-8000-00805f9b34fb;98f00001-3788-83ea-453e-f52244709ddb;
Appearance=0x0180
```

attributes:
```
[1]
UUID=00002800-0000-1000-8000-00805f9b34fb
Value=1800
EndGroupHandle=9

[10]
UUID=00002800-0000-1000-8000-00805f9b34fb
Value=1801
EndGroupHandle=13

[14]
UUID=00002800-0000-1000-8000-00805f9b34fb
Value=98F00001378883EA453EF52244709DDB
EndGroupHandle=65535
```

**Comment by stsergo** [comment]
Ещё заметил. при подключении к телефону, бризер сразу же выходит из режима сопряжения.

**Comment by IATkachenko** [comment]
А ключи-то в нем есть?

**Comment by stsergo** [comment]
Видимо нет, я вывод вставил как есть в комментарий

**Comment by IATkachenko** [comment]
А `[bluetooth]# paired-devices` видит бризер в списке сопряженных устройств?
bluetoothctl, когда делали pair, запускали от рута или обычного пользователя?

**Comment by stsergo** [comment]
Видит
```
[bluetooth]# paired-devices
Device CB:86:F2:3F:3A:CB Br Lite
```
от рута

**Comment by IATkachenko** [comment]
У меня пока идей нет: 
 * летом мы делали обычный pair через bluetoothctl, как и вы. После этого подключение было без проблем.
 *  у вас сейчас, похоже, система думает что устройство сопряжено, а бризер полагает что нет.
Можно попробовать удалить каталог с маком бризера и перезапустить bluetooth. Это, по идее, скажет системе что сопряжения нет. После этого сделать pairing через bluetoothctl еще раз.

**Comment by stsergo** [comment]
Это я уже проверял. Ничего, к сожалению не поменялось. 
Я вот кстати в логе с телефона вообще не увидел pair команд. Попробую со вторым бризером

**Comment by stsergo** [comment]
Ну в целом поведение такое-же
mac бризера: *CE:FD

pair через bluetoothctl
```
[bluetooth]# pair F3:5A:82:01:CE:FD
Attempting to pair with F3:5A:82:01:CE:FD
[CHG] Device F3:5A:82:01:CE:FD Connected: yes
[CHG] Device F3:5A:82:01:CE:FD UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device F3:5A:82:01:CE:FD UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Device F3:5A:82:01:CE:FD UUIDs: 98f00001-3788-83ea-453e-f52244709ddb
[CHG] Device F3:5A:82:01:CE:FD ServicesResolved: yes
[CHG] Device F3:5A:82:01:CE:FD Paired: yes
[NEW] Primary Service
	/org/bluez/hci0/dev_F3_5A_82_01_CE_FD/service000a
	00001801-0000-1000-8000-00805f9b34fb
	Generic Attribute Profile
[NEW] Characteristic
	/org/bluez/hci0/dev_F3_5A_82_01_CE_FD/service000a/char000b
	00002a05-0000-1000-8000-00805f9b34fb
	Service Changed
[NEW] Descriptor
	/org/bluez/hci0/dev_F3_5A_82_01_CE_FD/service000a/char000b/desc000d
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
[NEW] Primary Service
	/org/bluez/hci0/dev_F3_5A_82_01_CE_FD/service000e
	98f00001-3788-83ea-453e-f52244709ddb
	Vendor specific
[NEW] Characteristic
	/org/bluez/hci0/dev_F3_5A_82_01_CE_FD/service000e/char000f
	98f00002-3788-83ea-453e-f52244709ddb
	Vendor specific
[NEW] Characteristic
	/org/bluez/hci0/dev_F3_5A_82_01_CE_FD/service000e/char0011
	98f00003-3788-83ea-453e-f52244709ddb
	Vendor specific
[NEW] Descriptor
	/org/bluez/hci0/dev_F3_5A_82_01_CE_FD/service000e/char0011/desc0013
	00002902-0000-1000-8000-00805f9b34fb
	Client Characteristic Configuration
Pairing successful
[CHG] Device F3:5A:82:01:CE:FD Appearance: 0x0180
[Br Lite]# exit
```

info файл
```
[General]
Name=Br Lite
AddressType=static
SupportedTechnologies=LE;
Trusted=false
Blocked=false
Services=00001800-0000-1000-8000-00805f9b34fb;00001801-0000-1000-8000-00805f9b34fb;98f00001-3788-83ea-453e-f52244709ddb;
Appearance=0x0180
```

Через питон поведение аналогичное - пока в режиме сопряжения, данные забираются. 
Лог - [log2.txt](https://github.com/TionAPI/HA-tion/files/5704017/log2.txt)

В [дампе](https://jk-hor.ru/Rx8TY5diuc9xW7/bluetoothd-hci-latest1.pklg.zip) с телефона с этим бризером есть pair. 
и несколько больше обмена в SMP

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/18488041/102377232-806ad100-3fd5-11eb-9392-db4e58dbfeb3.png">

**Comment by IATkachenko** [comment]
в SMP обмене вижу обмен ключами, а с хоста он не происходит (судя по содержимому info).
Похоже нам нужно копать в сторону bluetooth стэка на вашей системе.
Можете через `btmon` собрать что происходит во время pair, например через bluetoothctl, чтобы мы могли сравнить?

**Comment by stsergo** [comment]
@IATkachenko Спасибо за помощь!. 

Проблема действительно была в стеке. 
Переставил стек. 
в bluetoothctl выполнил

**Comment by IATkachenko** [comment]
Ура!
Я пока issue оставлю открытым -- наш опыт надо перенести в wiki/документацию.

**Comment by foxoskol** [comment]
Хм, то ли я дурак то ли лыжи не едут.
У меня вот какая ситуация. Из HA пытаюсь добавить, вываливается ошибка:
![Безымянный](https://user-images.githubusercontent.com/71713159/102505866-90e18100-4093-11eb-92b8-70f796cf4596.jpg)

в логах bluetoothctl:
[NEW] Device E4:13:50:4E:A9:1B Br Lite
[NEW] Primary Service (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000a
        00001801-0000-1000-8000-00805f9b34fb
        Generic Attribute Profile
[NEW] Characteristic (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000a/char000b
        00002a05-0000-1000-8000-00805f9b34fb
        Service Changed
[NEW] Descriptor (Handle 0xfac4)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000a/char000b/desc000d
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
[NEW] Primary Service (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000e
        98f00001-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Characteristic (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_50_**_**_**/service000e/char000f
        98f00002-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Characteristic (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000e/char0011
        98f00003-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Descriptor (Handle 0x6384)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000e/char0011/desc0013
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
[CHG] Device E4:13:50:4E:A9:1B UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device E4:13:50:4E:A9:1B UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Device E4:13:50:4E:A9:1B UUIDs: 98f00001-3788-83ea-453e-f52244709ddb
[CHG] Device E4:13:50:4E:A9:1B ServicesResolved: yes
[CHG] Device E4:13:50:4E:A9:1B Appearance: 0x0180
[CHG] Device E4:13:50:4E:A9:1B ServicesResolved: no
[CHG] Device E4:13:50:4E:A9:1B Connected: no

при этом если посмотреть bt-device -l
Added devices:
Br Lite (E4:13:50:4E:A9:1B)

но в HA не добавляется.
Причем был какой то момент, добавился, но данные и возможность управления не появилась.

**Comment by IATkachenko** [comment]
@foxoskol, лучше было завести новое issue (это -- бесплатно), а то тут каша в итоге получится: не из чего не следует что ваша проблема такая же как обсуждалась здесь.

Завел #30.

**Comment by foxoskol** [comment]
окей, извините. подумал что сюда лучше. ушел в туда:).

**Comment by vtolstov** [comment]
а что в итоге в стеке обновили ? у меня подобное поведение на fedora 38 сейчас. Пеиринг проходит, в /var/lib/bluetooth данные есть, но HA ничего не получает.

**Comment by IATkachenko** [comment]
@vtolstov у нас с тех пор вот такой раздел в ВиКи появился, как раз про это https://github.com/TionAPI/HA-tion/wiki/Bluetooth#сопряжение-успешно-но-не-получается-получить-данные

У меня недавно стреляло такое, после обновления малины. Действия по ВиКи все починили.

А раскопки были про то что криво проходит BT сопряжение устройств. Я думаю были переставлены связанные с BT компоненты системы. И сделано то, что в ВиКи описано.

**Comment by IATkachenko** [comment]
> но через минут 40-50 коннект теряется.

По моему опыту -- это нормальное поведение. Судя по скринам, BT часть отрабатывает корректно. 
Никто соединение не перехватывает? Пультик или приложение, или MagicAir?
