### ISSUE TITLE
Работа с двумя бризерами

### ISSUE THREAD

**Issue by fishenebelny** [TionAPI/HA-tion#3]
Здравствуйте,

Как добавить 2 бризера в новом компоненте 1.2? Из configuration.yaml все успешно работало. А тут не получается... Подбирается только 1 бризер и второй никак не дает добавить.
Заранее спасибо!

В целом давно такое искал. Большое спасибо!

Сергей

**Comment by IATkachenko** [comment]
@fishenebelny, второй раз нажимаете +, добавляете еще раз c новым MAC адресом, задаете новое имя.
Должно все получиться.

**Comment by fishenebelny** [comment]
Да, действительно работает.
Большое спасибо!
