### ISSUE TITLE
Не добавляется Tion Lite

### ISSUE THREAD

**Issue by IATkachenko** [TionAPI/HA-tion#30]
**Метод установки Home Assistant**: docker-контейнер
**Версия компонента**: 1.4.2
**Модель бризера**: Lite

# Описание проблемы
Хм, то ли я дурак то ли лыжи не едут.
У меня вот какая ситуация. Из HA пытаюсь добавить, вываливается ошибка:
![Безымянный](https://user-images.githubusercontent.com/71713159/102505866-90e18100-4093-11eb-92b8-70f796cf4596.jpg)

в логах bluetoothctl:
[NEW] Device E4:13:50:4E:A9:1B Br Lite
[NEW] Primary Service (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000a
        00001801-0000-1000-8000-00805f9b34fb
        Generic Attribute Profile
[NEW] Characteristic (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000a/char000b
        00002a05-0000-1000-8000-00805f9b34fb
        Service Changed
[NEW] Descriptor (Handle 0xfac4)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000a/char000b/desc000d
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
[NEW] Primary Service (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000e
        98f00001-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Characteristic (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_50_**_**_**/service000e/char000f
        98f00002-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Characteristic (Handle 0xc2a1)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000e/char0011
        98f00003-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Descriptor (Handle 0x6384)
        /org/bluez/hci0/dev_E4_13_**_**_**_**/service000e/char0011/desc0013
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
[CHG] Device E4:13:50:4E:A9:1B UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device E4:13:50:4E:A9:1B UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Device E4:13:50:4E:A9:1B UUIDs: 98f00001-3788-83ea-453e-f52244709ddb
[CHG] Device E4:13:50:4E:A9:1B ServicesResolved: yes
[CHG] Device E4:13:50:4E:A9:1B Appearance: 0x0180
[CHG] Device E4:13:50:4E:A9:1B ServicesResolved: no
[CHG] Device E4:13:50:4E:A9:1B Connected: no

при этом если посмотреть bt-device -l
Added devices:
Br Lite (E4:13:50:4E:A9:1B)

но в HA не добавляется.
Причем был какой то момент, добавился, но данные и возможность управления не появилась.

_Originally posted by @foxoskol in https://github.com/TionAPI/HA-tion/issues/28#issuecomment-747501569_

**Comment by IATkachenko** [comment]
@foxoskol, утащил вашу проблему в новое issue, чтобы каши не было.

Приложите, пожалуйста, debug-логи Home Assistant в момент добавления.
Какую версию компонента используете?
К бризеру в момент подключения ТОЧНО никто не подключен (пульт, телефон)?

**Comment by foxoskol** [comment]
Вот логи:
2020-12-17 18:29:56 DEBUG (MainThread) [custom_components.tion.config_flow] Showing pair info
2020-12-17 18:29:57 DEBUG (MainThread) [custom_components.tion.config_flow] Real pairing step
2020-12-17 18:29:57 DEBUG (MainThread) [custom_components.tion.config_flow] {'model': 'Lite', 'name': '123', 'mac': 'E4:13:50:4E:A9:1B', 'keep_alive': 60, 'away_temp': 15, 'pair': True}
2020-12-17 18:29:57 DEBUG (MainThread) [tion_btle.tion] Pairing
2020-12-17 18:29:59 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral E4:13:50:**:**:**, addr type: random exception
2020-12-17 18:30:01 ERROR (MainThread) [custom_components.tion.config_flow] Cannot pair and get data. Data is {'model': 'Lite', 'name': '123', 'mac': 'E4:13:50:**:**:**', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; BTLEDisconnectError: Failed to connect to peripheral E4:13:**:**:**:**, addr type: random
2020-12-17 18:30:02 DEBUG (MainThread) [custom_components.tion.config_flow] Pair failed. Returning to first step

точно ничего, все BT устройства специально выключил.

**Comment by IATkachenko** [comment]
Те вот так прям сразу, без объявления войны `BTLEDisconnectError` во время connect()...

[bluetooth_le_tracker](https://www.home-assistant.io/integrations/bluetooth_le_tracker/)бризер в режиме сопряжения видит?

Что говорит bluetoothctl на попытку подключиться к бризеру (видимо без режима сопряжения будет сразу disconnect, а в режиме сопряжения все будет хорошо до тех пор пока он из него не выйдет)?

Пользователь от которого запущен HA добавлен в группу bluetooth (если о не root, конечно)?

Если пользователь не root, то `setcap` делали (как в конце статьи про bluetooth_le_tracker?

**Comment by foxoskol** [comment]
@IATkachenko HA стоит в докере на ubuntu. поэтому с правами на bluetooth проблем нет.
bluetooth_le_tracker  видит бризер, это первое что я проверил.

Я тоже обратил внимание на BTLEDisconnectError но не понимаю с чего вдруг.

**Comment by IATkachenko** [comment]
Ага, docker... Пора, наконец, и тут сделать template ;)

Нашел #27, где мы уже обсуждали проблемы (извините, сразу не признал что проблема не очень свежая). 
У вас, как я понимаю, в какой-то момент [заработал ](https://github.com/TionAPI/HA-tion/issues/27#issuecomment-745374824)[тестовый скрипт](https://github.com/TionAPI/HA-tion/issues/27#issuecomment-745365688).
Давайте восстановим это состояние здесь. Запустите, пожалуйста его сейчас (на актуальной версии модуля, 1.1.1)

**Comment by foxoskol** [comment]
Так, давайте тогда определимся, мы этот тестовый скрипт будем запускать на хостовой машине? или все же сразу в контейнере?

**Comment by IATkachenko** [comment]
С хоста, для начала, чтобы локализовать проблему: модуль или настройки контейнера/хоста.
Если с хоста ОК -- пойдем в контейнер.

**Comment by foxoskol** [comment]
Так, что то мне подсказывает, что вылезла болезнь ubuntu и BT. Сейчас крипт нивкакую не запускается, хотя снепшотов был откачен до состояния когда работал. Валится с той же ошибкой .BTLEDisconnectError.
Давайте так, я завтра раскатаю виртуалку с debian и 18 ubuntu и там потестируем.

**Comment by IATkachenko** [comment]
Никаких проблем, пишите. Но с вас потом пара букв про вашу проблему для https://github.com/TionAPI/HA-tion/wiki/Bluetooth ;)

**Comment by foxoskol** [comment]
Да хоть не пара:) я только за.
И да, проблема в ubuntu. Для затравки напишу сейчас, а завтра уже полноценные эксперименты.
Вообщем, тестовый скрипт отрабатывает. но вот как:
1. Запускаем тестовый скрипт первый раз, и получаем вот такой выхлоп:
DEBUG:tion_btle.tion:Pairing
WARNING:tion_btle.tion:Got Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random exception
Traceback (most recent call last):
  File "1.py", line 17, in <module>
    device.pair()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 469, in pair
    self._connect()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 311, in _connect
    raise e
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 300, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random
2. делаем следом DEBUG:tion_btle.tion:Pairing
WARNING:tion_btle.tion:Got Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random exception
Traceback (most recent call last):
  File "1.py", line 17, in <module>
    device.pair()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 469, in pair
    self._connect()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 311, in _connect
    raise e
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 300, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random
2. Делаем следом modprobe -r btusb ; sudo modprobe btusb
3. запускаем повторно тестовый скрипт и получаем выхлоп
DEBUG:tion_btle.tion:Pairing
WARNING:tion_btle.tion:Got Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random exception
Traceback (most recent call last):
  File "1.py", line 17, in <module>
    device.pair()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 469, in pair
    self._connect()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 311, in _connect
    raise e
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 300, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random
root@homeassistant:/usr/tion_python-1.1.1# sudo modprobe -r btusb ; sudo modprobe btusb
root@homeassistant:/usr/tion_python-1.1.1# sudo modprobe -r btusb ; sudo modprobe btusb
root@homeassistant:/usr/tion_python-1.1.1# sudo modprobe -r btusb ; sudo modprobe btusb
root@homeassistant:/usr/tion_python-1.1.1# python3.8 1.py E4:13:50:4E:A9:1B
DEBUG:tion_btle.tion:Pairing
DEBUG:tion_btle.tion:Enabling notification
DEBUG:tion_btle.tion:Delegation enabled
DEBUG:tion_btle.tion:First read done
DEBUG:tion_btle.tion:enable_notification is done
DEBUG:tion_btle.tion:Connected. BT pairing ...
DEBUG:tion_btle.tion:Got response while sending pair command: {'rsp': ['mgmt'], 'code': ['success']}
DEBUG:tion_btle.tion:success
DEBUG:tion_btle.tion:Device-specific pairing ...
DEBUG:tion_btle.tion:Device pair is done
DEBUG:tion_btle.tion:disconnected
DEBUG:tion_btle.tion:Enabling notification
DEBUG:tion_btle.tion:Delegation enabled
DEBUG:tion_btle.tion:First read done
DEBUG:tion_btle.tion:enable_notification is done
DEBUG:tion_btle.tion:Doing _try_write. Attempt 1/3
DEBUG:tion_btle.tion:Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
DEBUG:tion_btle.lite:Collecting data
DEBUG:tion_btle.tion:Got data in 18 response 0049003a0a31120dd71f8f0000000086d8010a01
DEBUG:tion_btle.tion:Got data in 18 response 4018191b5f4ebb0247087e0207303a0060a0bb02
DEBUG:tion_btle.tion:Got data in 18 response 4000000000000000000000000100000100000000
DEBUG:tion_btle.tion:Got data in 18 response c000000000000a1419020406060000523f
DEBUG:tion_btle.lite:Got 0049003a0a31120dd71f8f0000000086d8010a01 from tion
DEBUG:tion_btle.lite:Got 4018191b5f4ebb0247087e0207303a0060a0bb02 from tion
DEBUG:tion_btle.lite:Got 4000000000000000000000000100000100000000 from tion
DEBUG:tion_btle.lite:Got c000000000000a1419020406060000523f from tion
DEBUG:tion_btle.lite:Data is 86d8010a0118191b5f4ebb0247087e0207303a0060a0bb020000000000000000000000010000010000000000000000000a1419020406060000
crc is: 0000
header._package_size = bytearray(b'')
header_commad_type =
DEBUG:__main__:Result is {'state': 'off', 'heater': 'off', 'heating': 'off', 'sound': 'on', 'mode': 'mixed', 'out_temp': 25, 'in_temp': 24, 'heater_temp': 10, 'fan_speed': 1, 'filter_remain': 44.136377314814816, 'time': '20:02', 'request_error_code': 0, 'model': 'Lite', 'code': 200, 'device_work_time': 530.6796296296296, 'electronic_work_time': 142.0751736111111, 'electronic_temp': 27, 'co2_auto_control': '0', 'filter_change_required': '0', 'light': 'on'}
INFO:__main__:Initial state: device is off, light is on, sound is on, heater is off, fan_speed is 1, target_temp is 10

Это однозначно проблема ubuntu. Для справки модуль BT у меня CSR8510A. В чем конкретно дело, завтра поиграюсь с разными виртуалками и скажу точно.

**Comment by IATkachenko** [comment]
Там еще хвост странный
```
DEBUG:tion_btle.tion:Pairing: command not found
```
я даже не соображу откуда он может быть: это происходит после последнего `_LOGGER.info()`, но идет из класса `tion`. А там такое может быть только в паре с `_LOGGER.critical`, да и то в виде `TionException`, которые в скрипте ловить никто не должен...

**Comment by foxoskol** [comment]
Проблема похоже однозначно в хост системе, пока бодаюсь с системой. Тестирую на двух разных чипах.

**Comment by foxoskol** [comment]
Тк, ну чтож, докопался до того, что перекатил ubuntu на 18.04 поменял адаптер BT. и в итоге получил вот такой выхлоп:
DEBUG:tion_btle.tion:Pairing
WARNING:tion_btle.tion:Got Device disconnected exception
Traceback (most recent call last):
  File "1.py", line 17, in <module>
    device.pair()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 469, in pair
    self._connect()
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 311, in _connect
    raise e
  File "/usr/tion_python-1.1.1/tion_btle/tion.py", line 301, in _connect
    for tc in self._btle.getCharacteristics():
  File "/usr/local/lib/python3.6/dist-packages/bluepy/btle.py", line 508, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.6/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.6/dist-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected

теперь у меня сомнения на счет проблемы в системе. Это выхлоп тестового крипта.

**Comment by foxoskol** [comment]
Так, все разобрался и все заработало. Проблема была исключительно в хост системе, и есть одна особенность на ubuntu. Если с первого раза не срабатывает pair выбивает с ошибкой, то нужно на бризере повторно активировать режим сопряжения, а в плагине убрать галку need pair.

**Comment by IATkachenko** [comment]
Добавил описание вашего случая на https://github.com/TionAPI/HA-tion/wiki/Bluetooth
