### ISSUE TITLE
При перезагрузке HA выключается обогрев. 

### ISSUE THREAD

**Issue by vekser** [TionAPI/HA-tion#32]
Версия HA-tion 1.4.2

**Comment by IATkachenko** [comment]
Проблема растет из #19.
Чтобы это поправить нужно при инициализации говорить что текущее состояние -- это одновременно и прошлое. Возможно, такое решение сработает.

**Comment by IATkachenko** [comment]
Проблема все еще актуальна? В v1.6 была несколько изменена логика работы с состояниями, что могло, в том числе, исправить и эту проблему.
