### ISSUE TITLE
Проблема сопряжения с Тионом при внешнем адаптере

### ISSUE THREAD

**Issue by fishenebelny** [TionAPI/HA-tion#35]
Здравствуйте,

Купмл себе внешний адаптер с антенной, чтобы проверить как будет работать интеграция через него по сравнению со стандартным адаптером.
При сопряжении получаю ошибки ниже.

Рекомендации из вики сделал:
1. Bluetoothctl бризер видит и спаривается с ним (вижу в dpaired-evices)
2. Пользователь от которого запускаетс HA в группе bluetooth (со встроенным адаптером все работало)
3. выполнены setcap из описания bluetooth_le_tracker (разово, после перезагрузок не дедал)
4. --compat добавлено в /etc/systemd/system/bluetooth.service для строки Exec...
5. Права на /var/run/sdp даны
6. Права пользователю от которого запускается HA на блютуз даны (policy bla bla)

Малина перезапускается и права на фацл /var/run/sdp вылаются вручную для группы bluetooth.

БТ адвптер с али - Bluetooth 4,0 CSR
https://a.aliexpress.com/_9I5e4l

Версия интеграции самая последняя 1.5.

Любая помощь приветствуется.
Заранее спасибо!

Logger: tion_btle.tion
Source: /srv/homeassistant/lib/python3.7/site-packages/tion_btle/tion.py:503
First occurred: 21:57:26 (1 occurrences)
Last logged: 21:57:26

bt pairing: could not pair! Permission denied. Check permissions at host. Ignore it if all goes well

Logger: tion_btle.tion
Source: /srv/homeassistant/lib/python3.7/site-packages/tion_btle/tion.py:372
First occurred: 21:57:30 (2 occurrences)
Last logged: 21:57:34

_enable_notifications: got 'Device disconnected' while first read! Could not continue!

Logger: tion_btle.tion
Source: /srv/homeassistant/lib/python3.7/site-packages/tion_btle/tion.py:314
First occurred: 21:57:30 (2 occurrences)
Last logged: 21:57:34

Got BTLEDisconnectError:Device disconnected

**Comment by fishenebelny** [comment]
Получилось добавить ичпользуя заметку "вроде добавляется, но не добавляется". В paired-devices действительно появился только после спаривания через компонент.
Потом добавил без необходимости спаривания.
Но до этого подобные действия делал и были проблемы.

**Comment by IATkachenko** [comment]
"вроде добавляется, но не добавляется" в wiki еще нет. Скиньте, пожалуйста, ссылку на статью которая помогла -- добавлю в базу знаний.

**Comment by fishenebelny** [comment]
Вот эта секция помогла - Сопряжение успешно, но не получается получить данные

**Comment by fishenebelny** [comment]
Вот что сейчас получается.
Устройство появляется в paired-devices в bluetoothctl в следующем случае:
1. Захожу в bluetoothctl
2. Запускаю pair<mac>
3. Перехожу в НА
4. Начинаю процесс спаривания через НА
5. В bluetoothctl успешно добавляется в paired-devices
6. В НА пишет не удалось спариться, а когда пытаюсь добавить без спаривания пишет не удалось получить тестовые данные. 

При этом второй бризер работсет окей. Ошибки схожие с тем, что было ранее.
 
Ничего не понимаю.

**Comment by fishenebelny** [comment]
Стало еще веселее. Бризер добавился в НА. Получает статусы о состоянии (включен. Выключен, остаток фильтра и т.п.). Но не управляется и в paired-devices его нет.

Чтобы этого добиться всю малину перенес в соскднюю комнату в прямую вилимость этого проблемного Тиона. При этой начальный Тион с большего расстояния прекрасно управляется, хотя его учловия ухудшились...
 Выглядит как фантастика.

**Comment by fishenebelny** [comment]
Появился в paired-devices. Вивдимо проблема отображения bkuetoothctl

**Comment by fishenebelny** [comment]
Из всего этого могу предположить только следующее:
1. Чтобы исключить проблемы доступности Тионов по БТ надо их сопрягать в зоне прямой видимости.
2. У Тионов внутри могут быть разные модули БТ, которые отличаются по мощности. 

c4:64:95:c3:5e:79 - Слабый (работает только в зоне прямой видимости)
d5:91:dd:fc:1a:60 - Более мощный (работает через стенку)

Буду рад обратной связи.

**Comment by IATkachenko** [comment]
Сопряжение или прошло или нет. Процесс состоит из двух частей: BT сопрряжение и запись в Тион информации что с этим устройством можно работать. Причем внутри Тиона, похоже, первое делается только после второго.

Модули, действительно, могут быть разные. Как это проверить я не знаю. Тут как MAC-адресами сетевых карт все легко выяснить не получится.

**Comment by IATkachenko** [comment]
Раз проблема решена и описана в Wiki -- закрываю.
