### ISSUE TITLE
Отправка нераспознанного режима

### ISSUE THREAD

**Issue by fishenebelny** [TionAPI/HA-tion#37]
Пытаюсь выключить Тион через карточку с выставление режима "выключено". Ничего не происходит.
В логах ошибка ниже. Версия 1.5. 
Можете подсказать в чем проблема?

Logger: custom_components.tion.climate
Source: custom_components/tion/climate.py:265
Integration: Tion breezer (documentation)
First occurred: 13:42:35 (1 occurrences)
Last logged: 13:42:35

Unrecognized hvac mode: None

**Comment by fishenebelny** [comment]
Поогает выйти из ситуации смена режима на "вентиляцию", а потом на "выключен".

**Comment by IATkachenko** [comment]
Бризер S3, как я помню?

Кажется, вижу где может быть проблема.

**Comment by fishenebelny** [comment]
S3.  Есть такое подозрение, что это и есть та проблема про которую я писал в другой ветке.

**Comment by fishenebelny** [comment]
Появилась после того, как сервисом выставил режим проветривания. Редим проветривания выставлял командой ниже. При жтом брищер вклбчается, редим оьогрев/вентиляция показывает. Но потом 1 тион выключился, а другой выдавал вот такую ошибку.

climate.set_fan_mode, fan_mode: 6

**Comment by IATkachenko** [comment]
Логи. Нужны debug-логи. Со слов я не понимаю что происходит и не могу воспроизвести.
в configuration.yaml нужно прописать
```
logger:
  default: warning
  logs:
    custom_components.tion: debug
    tion_btle.tion: debug
    tion_btle.s3: debug
```
и прислать фрагмент home-assistant.log в момент возникновения проблемы.

**Comment by IATkachenko** [comment]
Пока мое единственное предположение, что вы делаете это (climate.set_fan_mode -> нажать кнопку выключения на карточке) слишком быстро и HA не успевает узнать что бризер включился.

**Comment by fishenebelny** [comment]
Уже смотрел. Удалил все. Как повторится буду смотреть внимательнее.
Попробовал повторить - тоже не получилось.
Могу сказать только одно - статусы точно обновились, так как я проверяю сечас как стабильно все это работает. И уже думал, вто опять проьлема со связью, как в логах увидел эту нераспознанную команду.

**Comment by IATkachenko** [comment]
> Уже смотрел. Удалил все. Как повторится буду смотреть внимательнее.
Присылайте homae-assistant.log в debug режиме сразу: он объясняет то что происходит с системой на самом деле. Логи UI и объяснение последовательности действий не всегда говорят о том что же там внутри происходило.
