### ISSUE TITLE
сам меняется режим работы

### ISSUE THREAD

**Issue by MihVS** [TionAPI/HA-tion#38]
До обнов у меня настроено было по принципу перепроверки заданного статуса и отправки команды вновь если статус не изменился, но после обновления стал замечать что это не стало работать. Отправленная команда бывает возвращается с большой задержкой. Т.е. например изменил я режим с обогрева на вентиляцию, всё изменилось, делаю проверку всё ок и примерно через 30 сек может статус сам вернутся на обогрев. Не знаю с чем это связано, но очень неудобно стало контролировать исполнение команд. Если я убираю проверку, то команды не всегда проходят с первого раза. 
Откатился к версии v1.4.3 пока всё ок, тестирую.

**Comment by IATkachenko** [comment]
Можно по подробнее как это все выглядит в виде автоматизаций?
Как именно контролируете статус? Происходит ли реальное изменение режима работы бризера?

Ну и debug-log, конечно, хотелось бы увидеть.

Возвращение к предыдущему значению -- типичная ситуация для случая если команда изменения не сработала на бризере и при следующем опросе состояния мы получаем обратно старый, не измененный статус.

**Comment by MihVS** [comment]
в автоматизации это выглядит примерно так, отправляю команду на включение обогрева и запускаю таймер по истечению проверяю статус режима тиона, если изменился то норм, если нет то отправляю снова команду и запускаю этот же таймер. И так пока не изменится режим тиона. Реальное изменение режима работы бризера происходит, и спустя какое-то время происходит обратная смена режима(но это не всегда но в обновлении1.5 это происходит)
Лог пока предоставить не могу, сейчас тут преобразую конфиг, всё настрою протестю на 1.4 и потом можно будет обновиться и логи глянуть.
Такое ощущение что с версии 1.5 поданные команды становятся в очередь на исполнение, и при отправке мой конфиг проверяет статус, всё поменялось и радуется, но спустя секунд 30 до бризера доходит ещё одна команда и режим меняется обратно. Пробовал отключать повторные отправки команд, тогда не всегда команды доходят до тиона. было бы зорова конечно что бы я не парился на счет исполнения бризером команды, а интеграция сама реализовывала типа таких проверок и добивалась исполнения. Что бы лишних автоматизаций и таймеров не городить.

**Comment by IATkachenko** [comment]
Нет, очередей никаких не появилось.

Между 1.4.3 и 1.5.1 в части общения с бризером не менялось ничего.
В 1.6.0 [появилась ](https://github.com/TionAPI/HA-tion/compare/v1.5.1...v1.6.0) группировка последовательных команд бризеру в одно соединение (раньше для этого требовалось 2  раза подключаться-отключаться от бризера). 

[Те после set сразу делается update, без отключения от бризера](https://github.com/TionAPI/HA-tion/compare/v1.5.1...v1.6.0#diff-f797d636dfa49d4bd9586cb6e98178229ed72a14aa8b9de1b40d6cee93846180R431)
Может быть проблема в этом и теперь нужна небольшая задержка между этими действиями. Но это произошло в 1.6, а у вас проблемы с 1.5.

Конкретно в части обогрев/вентиляция изменений еще не было вообще никаких.

Если вы говорите что проблема при переходе на 1.5, то там [поднималась версия модуля](https://github.com/TionAPI/HA-tion/compare/v1.4.3...v1.5.1#diff-de4fd50f8416ee78a8357a8c4544b93fe7a2fa7209e80bb6cfb59275614f4c2aR9).

В модуле между 1.1.2 и 1.1.4 ничего примечательно [не происходило](https://github.com/TionAPI/tion_python/compare/v1.1.2...v1.1.4).

Очень интересно посмотреть на debug-логи.

**Comment by IATkachenko** [comment]
Воспроизвел у себя.
Проблема действительно в группировке и проявляется при смене режимов и темературы.

**Comment by IATkachenko** [comment]
И да, еще некорректное поведение было во внутренней логике, связанный с этим блоком. 
Так что, возможно, группировка команд не виновата.
