### ISSUE TITLE
Сенсор filters remain отдает дни с дробной частью

### ISSUE THREAD

**Issue by stsergo** [TionAPI/HA-tion#40]
Заметил, что после какого-то из обновлений компонента в HA сенсор фильтров стал показывать дробную часть:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/18488041/107231201-113bb700-6a31-11eb-9d20-3bd3f86c4be2.png">
Кажется где-то потерялось округление.

**Comment by IATkachenko** [comment]
И с какой-то бешеной точностью.
Как лучше сделать:
  * отдавать 1 знак после запятой, с округлениям по правилам;
  * отдавать целое число с округлениям по правилам;
  * округлять в меньшую сторону до целого числа (отбрасывать дробную часть);
  * округлять в большую сторону до целого числа;

**Comment by stsergo** [comment]
Т.к. это дни, то думаю, что правильнее всего округлять в большую сторону до целого числа. 
В последний день будет верное поведение - остаётся 1 (текущий) день.

**Comment by IATkachenko** [comment]
Это должно быть исправлено начиная с 1.5.1.
@stsergo, можете подтвердить что сейчас у вас проблема не актуальна?

**Comment by stsergo** [comment]
Видимо что-то пошло не так, но проблема у меня до сих пор наблюдается :( 1.7.0 сейчас стоит
<img width="365" alt="image" src="https://user-images.githubusercontent.com/18488041/111387640-1b4f7600-86bf-11eb-8545-bd9e6747f1be.png">

**Comment by IATkachenko** [comment]
Понял, вижу.
Сейчас поправим.
