### ISSUE TITLE
Поддержка О2

### ISSUE THREAD

**Issue by AX0411** [TionAPI/HA-tion#42]
ДД. 
Добавить поддержку О2 не планируется?
Как S3 или Lite его подключить не получится?

**Comment by IATkachenko** [comment]
O2, на сколько мне известно, не управляется по Bluetooth, а для его управления используется ИК пульт.
Значит подойдет любой умный ИК пульт и что-то вроде https://community.home-assistant.io/t/smartir-control-your-climate-tv-and-fan-devices-via-ir-rf-controllers/100798 (может уже из коробки что-то сделали -- просто первая ссылка в google)

**Comment by AX0411** [comment]
О2 с поддержкой МА управляется по бт с этой самой МА. Такой О2 у меня есть, МА нет (есть клирграсс). Подключить как S3 или Lite не получилось (но я пока разбираюсь)

**Comment by AX0411** [comment]
https://tion.ru/shop/breezer-tion-o2-mac/
С МА работает, проверял.

**Comment by IATkachenko** [comment]
Если есть MA -- то https://github.com/airens/tion_home_assistant поможет добавить бризер в HA.
Если хочется через эту интеграцию, то нужен дамп обмена по BT и описание того что происходит на бризере в эти момент.
