### ISSUE TITLE
Add S4 support

### ISSUE THREAD

**Issue by Zorgino** [TionAPI/HA-tion#45]
Waits for https://github.com/TionAPI/tion_python/issues/22

**Comment by Zorgino** [comment]
@IATkachenko, create a branch for s4, please

**Comment by IATkachenko** [comment]
I'll create release with S4 support in few days.

ps. We could not use git+https link to install module in production, it should be direct module version from pypi.

**Comment by Ravexkgd** [comment]
После обновления на 1.8.0 S4 перестал отвечать на запросы и отдавать информацию.
До обновления, хоть и сыпал ошибку после отправки данных, но работал.
Logger: custom_components.tion.config_flow
Source: custom_components/tion/config_flow.py:96

Could not get data from breezer. result is {}, error: ('Lite _get_data_from_breezer', 'Could not get breezer state')

**Comment by IATkachenko** [comment]
@Ravexkgd. откройте новое Issue, пожалуйста.
Поддержка S4 появилась в 1.8.0, так что до обновления на 1.8.0 S4 работать не мог.
