### ISSUE TITLE
Не запускается интеграция (does not have a valid version key)

### ISSUE THREAD

**Issue by UnnamedHero** [TionAPI/HA-tion#48]
## Общая информация
  * **версия Home Assistant**: 2021.6.4
  * **способ установки Home Assistant**:
    [ ] venv
    [Х ] Docker
    [ ] Home Assistant OS
 * **версия компонента**: 1.7.2
 * **модель бризера**:  Lite 
 * **версия python-модуля**: 

[X] в момент проявления проблемы к бризеру никто не подключен
[X] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[X] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 

Не устанавливается интеграция 
## Debug-log
```
2021-06-14 18:36:17 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'tion' does not have a valid version key (None) in the manifest file and was block
ed from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```

## Как можно воспроизвети вашу проблему
0. ОС - ubuntu 21.04 server
1. После установки модуля через hacs не могу добавить саму интеграцию в "настройки"-"интеграция"
2. В логах - информация выше.
содержимое /custom_components/tion/manifest.json
```
{
  "domain": "tion",
  "name": "Tion breezer",
  "documentation": "https://github.com/TionAPI/HA-tion/wiki",
  "dependencies": [
    "fan"
  ],
  "requirements": [
    "tion-btle==1.2.0"
  ],
  "codeowners": [
    "@IATkachenko"
  ],
  "config_flow": true
}
```
Update 1
Если руками прописать 
```
...
  "config_flow": true,
  "version": "1.7.2"
}
```
ругаться перестаёт, но интеграцию добавить не могу - интеграция не находится через поиск.

**Comment by IATkachenko** [comment]
Спасибо, придется форсить 1.7.3: HACS почему-то берет именно тэг, а не архив из релизов...

А вот то что через поиск не находится после исправления манифеста -- странно. "Tion breezer" должен быть, если он нашел манифест.

**Comment by IATkachenko** [comment]
v1.7.3 сделал.
Проверьте, пожалуйста что она нормально добавляется и находится.
Если не находится -- проверю у себя, локально, через докер.

**Comment by UnnamedHero** [comment]
1.8.0 работает без шаманства. Спс.
