### ISSUE TITLE
Отваливаются почему-то тионы и периодически не работает управление.

### ISSUE THREAD

**Issue by kalend** [TionAPI/HA-tion#60]
Приветствую.

Стоит HA на Raspberry PI4B. 
HA установлен в docker, имеется HACS и установленный HA-Tion
HA version: **core-2021.9.6**
HA-Tion version: **v2.0.0**

Описание проблемы:

Имеем несколько Tion lite, подключенных через Raspberry PI 4. Выглядит так, будто периодически Тионы отваливаются по Bluetooth. Интеграция работает через раз - периодически выдает ошибки. Куда копать пока не понял. В bluetoothctl видно как Тионы подключаются и отключаются. 

```
bluetoothctl 
Agent registered
[bluetooth]#  connect FC:2C:C1:7C:F9:DC
Attempting to connect to FC:2C:C1:7C:F9:DC
[Br Lite]# connect F9:EF:AC:46:D0:5C
Attempting to connect to F9:EF:AC:46:D0:5C
[CHG] Device F9:EF:AC:46:D0:5C Connected: yes
Connection successful
[CHG] Device F9:EF:AC:46:D0:5C ServicesResolved: yes
[CHG] Device F9:EF:AC:46:D0:5C Paired: yes
[CHG] Device F9:EF:AC:46:D0:5C ServicesResolved: no
[CHG] Device F9:EF:AC:46:D0:5C Connected: no
...
```

В логах HA:
```
Error doing job: Task exception was never retrieved
21:31:40 – (ОШИБКА) Tion breezer (кастомная интеграция)
Response is {}
21:31:40 – (КРИТИЧЕСКАЯ ОШИБКА) Tion breezer (кастомная интеграция)
Got Device disconnected while read in handleNotification. May continue working.
21:31:40 – (ПРЕДУПРЕЖДЕНИЕ) /usr/local/lib/python3.9/site-packages/tion_btle/tion.py - первое сообщение получено 19:04:10 и повторялось 2 раз
Error executing service: <ServiceCall climate.set_temperature (c:d9a8282f48fce414ccfd4f0f9146ca78): temperature=7.0, entity_id=['climate.gostevaya']>
21:30:57 – (ОШИБКА) Tion breezer (кастомная интеграция) - первое сообщение получено 21:18:29 и повторялось 2 раз
Got BTLEDisconnectError:Device disconnected
21:30:57 – (ПРЕДУПРЕЖДЕНИЕ) /usr/local/lib/python3.9/site-packages/tion_btle/tion.py - первое сообщение получено 19:03:07 и повторялось 76 раз
_enable_notifications: got 'Device disconnected' while first read! Could not continue!
21:30:37 – (КРИТИЧЕСКАЯ ОШИБКА) /usr/local/lib/python3.9/site-packages/tion_btle/tion.py - первое сообщение получено 19:15:11 и повторялось 3 раз
```

**Comment by IATkachenko** [comment]
@kalend, в v2.1.2 @kizill это, похоже, поправил.
После обновления лучше стало?

**Comment by kalend** [comment]
По ощущениям железки себе спокойно управляются и реагируют. Однако в логах HA жуть творится. Вот пример за сегодня. Может убрать логирование столь детальное в дебаг или таймауты и кол-во коннектов увеличить, чтобы ругань не сыпала так часто?

Logger: tion_btle.tion
Source: /usr/local/lib/python3.9/site-packages/tion_btle/tion.py:361 
First occurred: 11 января 2022 г., 20:17:23 (435 occurrences) 
Last logged: 12:11:28

Got BTLEDisconnectError:Failed to connect to peripheral d0:9b:f3:17:44:0d, addr type: random
Got BTLEDisconnectError:Failed to connect to peripheral fc:2c:c1:7c:f9:dc, addr type: random
Got BTLEDisconnectError:Failed to connect to peripheral F9:EF:AC:46:D0:5C, addr type: random
Got BTLEDisconnectError:Device disconnected

**Comment by IATkachenko** [comment]
Логируется неудачная попытка сделать connect внутри python-модуля, что само по себе не нормально.
Глянул свои логи -- у меня тоже самое, так что будет возможность поковырять.

**Comment by kalend** [comment]
Я думаю, что причина кроется в timeout. Полагаю, что эти железки работают так: делается connect, команда выполняется и они по bluetooth отключаются. При каждом запросе-изменении идет повторный connect. Это я проверял руками, когда делал connect по bluetooth к Tion. Полагаю, что при попытке сделать connect из интеграции есть задержка для первого запроса и нужно его повторить (кстати иногда замечал на предыдущей версии, что Тионы управляются со второго, а не с первого раза, что подтверждает сей факт) и видимо по таймауту идет логирование. Если таймауты увеличить или сделать повторные запросы без фиксации ошибки в логах, то возможно это полечит проблему.

**Comment by IATkachenko** [comment]
Да, общая схема действительно такая: connect - команда - disconnect. Если команд несколько, то они группируются в одну пачку. Сделано это чтобы к бризеру можно было подключиться пультом/приложением между опросами. 
На DEBUG уровне для `tion_btle.tion` хорошо видно как это происходит:
Нормальный запрос, без ошибки
```
2022-01-12 14:15:07 DEBUG (MainThread) [tion_btle.tion] Connecting
2022-01-12 14:15:08 DEBUG (MainThread) [tion_btle.tion] Enabling notification
```

С ошибкой
```
2022-01-12 14:18:07 DEBUG (MainThread) [tion_btle.tion] Connecting
2022-01-12 14:18:08 WARNING (MainThread) [tion_btle.tion] Got BTLEDisconnectError:Failed to connect to peripheral RR:RR:RR:RR:RR:RR, addr type: random
2022-01-12 14:18:08 DEBUG (MainThread) [tion_btle.tion] Will try again.
2022-01-12 14:18:10 DEBUG (MainThread) [tion_btle.tion] Connecting
2022-01-12 14:18:11 DEBUG (MainThread) [tion_btle.tion] Enabling notification
```
Происходит все здесь: https://github.com/TionAPI/tion_python/blob/6f25f1dcb5e231a7b77ba98fa80c4ee43fc5559b/tion_btle/tion.py#L345

Мне там сейчас не очень нравится кусок с определением характеристик. И, думаю, виноват именно этот блок.

Я у себя еще поэкспериментирую на эту тему, но дело явно не в timeout, поскольку `BTLEDisconnectError` прилетает мгновенно.

Не фиксировать ошибку я тоже не буду: это только маскирует проблему.
Если сильно мешает -- можно в настройках логирования указать в `configuration.yaml`:
```yaml
logger:
  logs:
    tion_btle.tion: critical
```
Тогда эти варнинги от модуля сыпаться в лог не будут.

**Comment by IATkachenko** [comment]
Нет, этот блок работает корректно.
```
2022-01-12 14:44:32 DEBUG (MainThread) [tion_btle.tion] Connecting
2022-01-12 14:44:32 DEBUG (MainThread) [tion_btle.tion] Connection_status is disc
2022-01-12 14:44:32 WARNING (MainThread) [tion_btle.tion] Got BTLEDisconnectError:Failed to connect to peripheral ..., addr type: random
2022-01-12 14:44:32 DEBUG (MainThread) [tion_btle.tion] Will try again.
```
Куда копать я понял. В ближайшее время будет fix-релиз для этого и завел #65.
Это issue, раз пробелма решена, закрываю.
