### ISSUE TITLE
Tion 4s перестал пробрасываться в Homekit

### ISSUE THREAD

**Issue by ffrants** [TionAPI/HA-tion#75]
## Общая информация
  * **версия Home Assistant**: 2022.4.3
  * **способ установки Home Assistant**:
    [ ] venv
    [ ] Docker
    [V] Home Assistant OS
 * **версия компонента**: 2.2.1
 * **модель бризера**: 4S
 * **версия python-модуля**: 

[V] в момент проявления проблемы к бризеру никто не подключен
[V] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[V] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
Бризер пропал из Homekit после обновления HA на новую версию. К сожалению, не помню на какой именно версии всё поломалось

## Debug-log
```
Logger: homeassistant.components.homekit
Source: components/homekit/type_thermostats.py:293 
Integration: HomeKit (documentation, issues) 
First occurred: 08:51:55 (1 occurrences) 
Last logged: 08:51:55

Failed to create a HomeKit accessory for climate.tion_breezer_spalnya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 617, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 244, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 292, in __init__
    fan_modes = {
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 293, in <dictcomp>
    fan_mode.lower(): fan_mode
AttributeError: 'int' object has no attribute 'lower'
```

## Как можно воспроизвети вашу проблему
Пробросить бризер в homekit

**Comment by IATkachenko** [comment]
Похоже что компонент отдает fan_mode как число, а они уже давно на строковое представление в духе low, mid итд...
Посмотрю внимательнее в ближайшее время.

**Comment by IATkachenko** [comment]
v2.2.2 попробуйте, пожалуйста.
Проблема должна уйти.

**Comment by ffrants** [comment]
Может я что-то делаю не так, но ошибка не ушла. Компонент обновил через HACS

`Logger: homeassistant.components.homekit
Source: components/homekit/type_thermostats.py:293 
Integration: HomeKit (documentation, issues) 
First occurred: 18:45:13 (1 occurrences) 
Last logged: 18:45:13

Failed to create a HomeKit accessory for climate.tion_breezer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 617, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 244, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 292, in __init__
    fan_modes = {
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 293, in <dictcomp>
    fan_mode.lower(): fan_mode
AttributeError: 'int' object has no attribute 'lower'`

**Comment by IATkachenko** [comment]
А, понял... это не совсем то fan_mode, по которое я подумал... И это сейчас поправим.

**Comment by IATkachenko** [comment]
в 2.2.3 поправил и fan_mode**s**. Теперь должно сработать.

**Comment by ffrants** [comment]
Вау, спасибо! Теперь всё работает 🙏
Чтобы два раза не вставать:  можно ли как-то сделать так чтобы в хомките можно было выбрать скорость? Или это невозможно?

**Comment by IATkachenko** [comment]
Эм? С хомкитом не работаю так что не знаю.

По идее, отдается климатическое устройство, которое умеет про скорость.
По крайней мере HA у меня справляется рулить скоростью нормально. И Алиса тоже переключает по запросу.

**Comment by ffrants** [comment]
Да, в HA и в Алисе все отлично, а в homekit отдаётся только температура и режим (нагрев/охлаждение/выкл). Ну раз вы с хомкит сами не работаете, тогда ладно :)
![Uploading CF98EF13-E144-4F4D-83E7-C5FD7B8AB3EE.png…]()

**Comment by IATkachenko** [comment]
Могу вытащить отдельный input, на подобии того как сделано управление тем, откуда берется воздух. Или просто компонент fan отдавать. Выбирайте как вам удобнее и открывайте новое issue -- сделаю :)
