### ISSUE TITLE
Поддержка скорости вентилятора в Homekit

### ISSUE THREAD

**Issue by ffrants** [TionAPI/HA-tion#76]
## Общая информация
  * **версия Home Assistant**: 2022.4.6
  * **способ установки Home Assistant**:
    [ ] venv
    [ ] Docker
    [X] Home Assistant OS
 * **версия компонента**: 2.2.3
 * **Модель бризера**: 4S
 * **версия python-модуля**: 
 [X] в момент проявления проблемы к бризеру никто не подключен
 [X] bluetooth в системе работает корректно, действий из (WiKi)[https://github.com/TionAPI/HA-tion/wiki/Bluetooth] не требуется
 [X] проблема не похожа ни на одну из (FAQ)[https://github.com/TionAPI/HA-tion/wiki/FAQ]
## Краткое описание 
Сейчас скорость вентилятора не пробрасывается в Homekit. Я не особо специалист, но думаю что нужно прокинуть компонент fan, тогда бризер будет отображаться как 2 устройства (термостат и вентилятор) и можно будет менять скорость вентилятора. По крайней мере, так это работает с кондиционером (если что, могу приложить скриншоты как выглядит кондиционер в Homekit).

## Дополнительное описание
JFYI В хомките нельзя просто взять и выбрать нужную скорость, как, например, в Алисе или HA. Скорость вентилятора задаётся там в процентах, что конечно по идее не мешает сделать сколько угодно скоростей. Опять же, в примере кондиционера, можно выбрать только 33%, 66% и 100%, что в HA будет Low, Medium и High

**Comment by IATkachenko** [comment]
Посмотрю что можно сделать.

**Comment by IATkachenko** [comment]
Охх, какие же они "молодцы": у компонента `climate` скорость вентилятора -- строка, а у компонента `fan` -- проценты.

Собственно проблем никаких, если все пойдет хорошо -- к выходным появится что-то что можно будет тестировать.

**Comment by IATkachenko** [comment]
Можете попробовать версию из dev?
В ней в интеграцию добавлен Fan компонент, который умеет в проценты скорости.

**Comment by ffrants** [comment]
Я не очень ~~умный~~ умею ставить компоненты не через HACS, так что просто заменил все файлы в папке custom_components/tion на файлы из dev ветки. В итоге словил вот такую ошибку при запуске:
`Logger: homeassistant.setup
Source: setup.py:298 
First occurred: 14:45:36 (2 occurrences) 
Last logged: 14:45:40

Unable to prepare setup for platform tion.fan: Platform not found (No module named 'custom_components.tion.fan').`

**Comment by IATkachenko** [comment]
Все правильно сделали. 
А файл `custom_components/tion/fan.py` у вас есть? Может быть что-то в поддиректорию попало? Или с правми что-то не то?

**Comment by IATkachenko** [comment]
А можно ссылку на какое-нибудь руководство по установлению дружбы HomeKit и HomeAssistant? (кстати, мне нужно какое-нибудь специфичное оборудование чтобы у себя это проделать?)
Я подозреваю что не отдаю какое-нибудь нужное/важное свойство и поэтому fan не виден.

**Comment by ffrants** [comment]
Я так понимаю, что ничего специально делать не нужно, для того чтобы компонент пробросился в хомкит. [Вот дока](https://www.home-assistant.io/integrations/homekit/#supported-components), со списком поддерживаемых компонентов. 
Я не настоящий сварщик, но мне что-то подсказывает, что нужно копать в сторону [fan-modes](https://developers.home-assistant.io/docs/core/entity/climate#fan-modes) компонента climate. Т.е. если очень грубо, сделать из бризера кондиционер с точки зрения HA. Что в принципе логично. 
Как я уже писал, у меня есть кондиционер который настроен через [MQTT HVAC](https://www.home-assistant.io/integrations/climate.mqtt/), в HA он у меня отображается как объект а не как устройство и в homekit он виден как 2 девайса, термостат и вентилятор, которые как бы слеплены вместе и ими можно управлять с одной плитки (нативно homekit не умеет кондиционеры, на сколько я понимаю)
Чтобы проверить работу хомкита нужен любой iPhone или iPad. Нужно добавить homekit интеграцию в HA и отсканировать куаркод который оно сгенерирует, в приложении Дом.

**Comment by IATkachenko** [comment]
Ага... Там все чуть интереснее, чем с Алисой...
Попробую в ближайшее время у себя развернуть это добро.

**Comment by IATkachenko** [comment]
Пока вот такая фигня (https://community.home-assistant.io/t/heater-cooler-accessory-type-support/343778/3)
```
No, what I’m saying is that climate could be mapped to 2 types of Homekit services: [Thermostat](https://github.com/home-assistant/core/blob/a1637e4fce89f8078a8cff197d71fbe9c5b592e4/homeassistant/components/homekit/const.py#L144) or HeaterCooler. Homeassistant only supports exposing climate as Thermostat, but it would be great if we could choose which HK service to use when exposing it.
```
И https://github.com/home-assistant/core/issues/72173#issuecomment-1153118463
```
Home assistant needs to support a new homekit accessory type, currently climate is mapped to Thermostat and it needs to offer HeaterCooler as an additional service type. HeaterCooler has fan speed and swing properties as part of that accessory type.
```
Так что напрямую мы это сейчас сделать не можем, просто потому что HA это не позволяет в принципе.

Я сейчас попробую выкинуть fan в секцию "Управление", тогда, по идее, он должен прокинуться в HomeKit.

**Comment by IATkachenko** [comment]
Проверил. Такой способ работает.
В ближайшее время сделаю релиз: вентилятор будет выкидываться отдельным устройством.

**Comment by IATkachenko** [comment]
Добавлено в [v2.4.0](https://github.com/TionAPI/HA-tion/releases/tag/v2.4.0)
