### ISSUE TITLE
Не работает управление несколькими бризерами в версиях после 2.1.5

### ISSUE THREAD

**Issue by fishenebelny** [TionAPI/HA-tion#77]
## Общая информация
  * **версия Home Assistant**:2022.5.4
  * **способ установки Home Assistant**:
    [ ] venv
    [*] Docker
    [ ] Home Assistant OS
 * **версия компонента**: 2.2.4
 * **модель бризера**: S3
 * **версия python-модуля**: 

[x] в момент проявления проблемы к бризеру никто не подключен
[x] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[x] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
После перехода на версию 2.2.4 Тионы частично пропадают после перезагрузки HA. Старые сенсоры не переименовывал, а удалил старые интеграции, и добавил их заново. В таком виде все прекрасно работает до первой перезагрузки HA.
Ранее были два объекта:
1. climate.tion_1
2. climate.tion_2

Сейчас они были удалены, и добавлены уже с другими именами climate.tion_bedroom и climate.tion_kids.

## Debug-log
```
Скопируйте содержиме home-asssistant.log с включенным режимом отладки для интеграции.
От момена до действия до возникновения проблемы.
```

## Как можно воспроизвети вашу проблему
Сложно сказать воспроизведется ли она, но проблема возникла примерно после следующих действий:
1. Обновление с компонента 2.1.5 до 2.2.4 при существующих двух Тионах tion_1 и tion_2
2. Часть сенсоров после обновления стала серой и добавились новые с такими же именами. При этом Tion 1, если мне не изменяет память, стал недоступным. 
3. Серые сенсоры не удалял, а удалил интеграции к ним.
4. Перезагрузил HA
5. Добавил интеграции заново с такими же именами объектов tion_1 и tion_2
6. Все прекрасно работало. Даже в автоматизациях ничего менять не пришлось. 
7. Перезагрузил HA
8. Tion 1 отвалился и стал полнгость недоступен, а Тион 2 функционировал как положено
9. Удалил обе интеграции
10. Перезагрузил HA
11. Добавил заново тионы с другими именами Tion Bedroom и Tion Kids.
12. Все работает прекрасно
13. Перезагружаю HA - все отвалилось кроме сенсоров для Tion Kids. При этом сам Tion Kids недоступен и управлять им нельзя.

## Дополнительное описание
Есть подозрение что это может быть как-то связано с заметкой о том, что надо было переименовать сенсоры и тем, что у меня было 2 Тиона.

А вообще после решения проблем с Bluetooth все работает очень стабильно и никаких зависаний, отвалов и т.п. вообще не было. Большое спасибо!

**Comment by fishenebelny** [comment]
Вот что в логах есть. d5:91:dd:fc:1a:60 - Tion 2 (он же Kids).

2022-05-16 21:26:22 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tion platform for climate
  File "/config/custom_components/tion/climate.py", line 46, in async_setup_entry
    async_add_entities([TionClimateEntity(hass, tion_instance)])
  File "/config/custom_components/tion/climate.py", line 100, in __init__
  File "/config/custom_components/tion/__init__.py", line 158, in device_info
2022-05-16 21:26:22 ERROR (MainThread) [homeassistant.components.select] Error while setting up tion platform for select
  File "/config/custom_components/tion/select.py", line 24, in async_setup_entry
    entities: list[TionInputSelect] = [
  File "/config/custom_components/tion/select.py", line 25, in <listcomp>
    TionInputSelect(description, tion_instance, hass) for description in INPUT_SELECTS]
  File "/config/custom_components/tion/select.py", line 47, in __init__
  File "/config/custom_components/tion/__init__.py", line 158, in device_info
2022-05-16 21:26:35 WARNING (MainThread) [custom_components.tion.climate] Device d5:91:dd:fc:1a:60 is already configured!

**Comment by IATkachenko** [comment]
А можно полный лог, от момента загрузки на debug уровне тиона? Пока есть ощущение что оба тиона добавляются с одинаковым мак-адресом или в `.storage` остались хвосты.

Про то что сенсоры поменяются в релиз ноут я писал (но кто их читает... надо было, конечно, как breaking changes помечать).

**Comment by IATkachenko** [comment]
Проверяйте mac-адреса в настройках: HA явно говорит что сходил к обоим бризерам:
```log
2022-05-17 10:16:05 DEBUG (MainThread) [custom_components.tion] Finished fetching Tion Bedroom data in 1.917 seconds (success: True)
2022-05-17 10:16:07 DEBUG (MainThread) [custom_components.tion] Finished fetching Tion Kids data in 3.207 seconds (success: True)
```
А дальше приключения что unique_id на самом деле не такие и unique:
```
2022-05-17 10:16:07 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID d5:91:dd:fc:1a:60-in_temp already exists - ignoring sensor.tion_kids_input_temperature
2022-05-17 10:16:07 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID d5:91:dd:fc:1a:60-out_temp already exists - ignoring sensor.tion_kids_output_temperature
2022-05-17 10:16:07 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID d5:91:dd:fc:1a:60-filter_remain already exists - ignoring sensor.tion_kids_filters_remain
2022-05-17 10:16:07 ERROR (MainThread) [homeassistant.components.select] Platform tion does not generate unique IDs. ID d5:91:dd:fc:1a:60-mode already exists - ignoring select.tion_kids_air_mode
```

Собственно зачем я просил логи с самого начала: при загрузке HA в логи пишется какие бризеры он настраивает: https://github.com/TionAPI/HA-tion/blob/f443be731c0fb19462ffdc2c32a7cd6aeaf3bd03/custom_components/tion/__init__.py#L31

unique_id -- mac-адрес бризера.
И эти строки будут говорить о том чем именно интеграция будет пытаться управлять.

**Comment by fishenebelny** [comment]
Проверил настройки тионов. Маки разные как и положено.
Собственно после добавления все работало. А вот после перезагрузки первый Tion 1 отваливается.
На что я еще обратил внимание. У меня была автоматизация по изменению скорости тиона в зависимости от CO2. Она была настроена еще на версии компонента 2.1.5. После удаления всех интеграций и создания новых с другими именами в этих автоматизациях Тионы определились как положено. То есть какой-то ID как будто не поменялся несмотря на то, что я их добавлял с другими именами.

**Comment by fishenebelny** [comment]
Вот еще особенность. Для интеграции Tion Bedroom существует 2 Тиона. Туда также почему то попадает Tion Kids.

Tion Bedroom = Tion_1 = c4:64:95:c3:5e:79
Tion Kids = Tion_2 = d5:91:dd:fc:1a:60

![image](https://user-images.githubusercontent.com/67923540/168782192-0e69a247-4af2-41b4-851a-dd1e285acba0.png)
![image](https://user-images.githubusercontent.com/67923540/168782338-7860130c-826d-4bb4-b8fb-88a2a5d353be.png)
![image](https://user-images.githubusercontent.com/67923540/168782585-eac87085-9bcb-4424-8d4a-7e8d7fa779be.png)
![image](https://user-images.githubusercontent.com/67923540/168782670-aea2fbe6-ee42-4d85-a3e6-1ab5eb87a8b3.png)
![image](https://user-images.githubusercontent.com/67923540/168782757-943de909-b21a-4f94-aa56-ecb866d9a67c.png)

**Comment by IATkachenko** [comment]
Два устройства -- действительно не правильно.
Все еще хочу лог от начала загрзуки HA, чтобы понять что оно там себе думает.
Как соотносится то что мы видим с кодом посмотрю внимательнее на днях.

Когда доберусь до своего HA скажу куда сходить посмотреть на тему проверки того какие ID в HA живут.

**Comment by fishenebelny** [comment]
Ммм... А где лог посмотреть от загрузки? Я вроде сделал перезагрузку HA (без системы) и добавил все логи, что были.

**Comment by IATkachenko** [comment]
А, я все понял... ну не все, но многое... 
(от загрузки -- я имел ввиду от момента когда HA ругается на то что его заставляют работать с кастомной интеграцией)

Нужные мне сообщения в логе есть. Но они странные, поэтому я их не заметил
```
2022-05-17 10:16:03 INFO (MainThread) [custom_components.tion] Setting up None
...
2022-05-17 10:16:03 INFO (MainThread) [custom_components.tion] Setting up None 
```
Вот они два инстанса.

**Comment by IATkachenko** [comment]
Сломаось все v2.2.0, пробелме подвержены все последующие версии.
Я понимаю что не так, но пока нет возможности поправить.
Я предлагаю или использовать управление одним бризером, или откатиться до 2.1.5

**Comment by fishenebelny** [comment]
Спасибо! Буду ждать, а пока откачусь на 2.1.5.

**Comment by IATkachenko** [comment]
В общем виде fix готов.
После того как локально протестирую -- выкачу релиз. Думаю, в районе выходных это будет.

**Comment by fishenebelny** [comment]
Могу попробовать сегодня проверить.

**Comment by IATkachenko** [comment]
Все в ветке [i77](https://github.com/TionAPI/HA-tion/tree/i77) лежит.
После обновления нужно зайти в настройки бризера и нажать OK (можно ничего не менять).
После этого лучше перезапустить HA.
Во время запуска для каждого сконфигруированного бризера должно быть сообщения в логе
```
INFO (MainThread) [custom_components.tion] Setting up <МАК бризера>
```

**Comment by fishenebelny** [comment]
Вот такую вот ошибку выдает. Загружал все ручками. 

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 17:08:26 (1 occurrences)
Last logged: 17:08:26

Setup failed for custom integration tion: Unable to import component: cannot import name 'TION_SCHEMA' from 'custom_components.tion.const' (/config/custom_components/tion/const.py)

**Comment by IATkachenko** [comment]
Угу, поторопился я с одним преобразованием. Откатил его. Ветку обновил.
Но все же рекомендую дождаться когда у себя это запущу :) Будет проще и быстрее.

**Comment by fishenebelny** [comment]
Вот такие вот ошибки теперь.
Кнопки настроить на текущих объектах после перезагрузки нет. Или надо было после замены файлов сразу же нажать настроить?
![image](https://user-images.githubusercontent.com/67923540/174093569-029ac2d3-3dc2-4799-85bf-d3a8240e6159.png)


Logger: homeassistant.config_entries
Source: config_entries.py:320
First occurred: 17:27:29 (2 occurrences)
Last logged: 17:27:29

Error importing platform config_flow from integration tion to set up tion configuration entry: Exception importing custom_components.tion.config_flow

Logger: homeassistant.loader
Source: loader.py:635
First occurred: 17:27:29 (2 occurrences)
Last logged: 17:27:29

Unexpected exception importing platform custom_components.tion.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/tion/config_flow.py", line 122
    await self.async_set_unique_id(unique_id)
    ^
SyntaxError: 'await' outside async function

**Comment by IATkachenko** [comment]
У вас пока интеграция пока не грузится из за ошибок в коде.
Я не на столько хорош чтобы сразу писать рабочий код без тестов :(
Это тоже поправил.

**Comment by fishenebelny** [comment]
Все ошибаются ) У меня была возможность проверить, я проверил. 
Вам в любом случае большое спасибо за эту интеграцию.

**Comment by IATkachenko** [comment]
Погонял тесты. Переделал кучу всего.

Попробуйте, пожалуйста, сейчас (из ветки i77).

Он должен будет в лог, на уровне CRITICAL 2 раза (для каждого бризера) написать что исправляет проблему с Unique ID и попросить перезапустить HA.

Собственно HA нужно перезапустить и после этого на INFO уровне в логах станет видно правильное:
```
INFO (MainThread) [custom_components.tion] Setting up <МАК бризера>
```
для каждого бризера в системе.

**Comment by fishenebelny** [comment]
Доброе утро,

Опять ошибки выдает. Вот так вот теперь. Может быть имеет смысл из попробовать добавить заново?

Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.config_entries
Source: custom_components/tion/__init__.py:60
Integration: Tion breezer (documentation)
First occurred: 09:41:44 (2 occurrences)
Last logged: 09:41:44

Error setting up entry Tion Kids for tion
Error setting up entry Tion Bedroom for tion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tion/__init__.py", line 35, in async_setup_entry
    hass.data[DOMAIN][config_entry.unique_id] = TionInstance(hass, config_entry)
  File "/config/custom_components/tion/__init__.py", line 60, in __init__
    _LOGGER.critical(f"Unique id is None for {self.config_entry.title}! "
AttributeError: 'TionInstance' object has no attribute 'config_entry'

**Comment by IATkachenko** [comment]
Как обычно, хотел лучше -- получилось как всегда )
Fixed now.
Можно обновиться из ветки, а можно в 60 строке `custom_components/tion/__init__.py` заменить `self.config_entry.title` на `self._config_entry.title` (что в ветке и сделано).

**Comment by fishenebelny** [comment]
Теперь по всей видимости все работает. Есть две ошибки. Одна с сообщениями про unique id, другая про перезагрузку.

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.tion
Source: custom_components/tion/__init__.py:60
Integration: Tion breezer (documentation)
First occurred: 10:41:14 (2 occurrences)
Last logged: 10:41:14

Unique id is None for Tion Kids! Will fix it by using d5:91:dd:fc:1a:60
Unique id is None for Tion Bedroom! Will fix it by using c4:64:95:c3:5e:79

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.tion
Source: custom_components/tion/__init__.py:66
Integration: Tion breezer (documentation)
First occurred: 10:41:14 (2 occurrences)
Last logged: 10:41:14

Done! Please restart Home Assistant.

**Comment by fishenebelny** [comment]
Теперь работает. Но обнаружил 2 нюанса.
1. При настройке бризера нет галочки - "Need Pairing?"
![image](https://user-images.githubusercontent.com/67923540/174551987-dddec2ab-30b6-4de1-87ac-b25a1102abd7.png)

2. При попытке добавить новый бризер вылетает ошибка как на картине ниже.
![image](https://user-images.githubusercontent.com/67923540/174552102-7b3b73f1-9960-483e-bd3c-ae15049e3381.png)

**Comment by fishenebelny** [comment]
Большое спасибо!

**Comment by IATkachenko** [comment]
Нет, само закроется, когда правки будут в master и, соответственно, релизе.

**Comment by fishenebelny** [comment]
Я вот это делал -
"Можно обновиться из ветки, а можно в 60 строке custom_components/tion/__init__.py заменить self.config_entry.title на self._config_entry.title (что в ветке и сделано)."

А до этого вск файлики ручками по одному из архива i77 скопировал. В том числе и в папку translations.

**Comment by IATkachenko** [comment]
Странно... А можно на ваш `translations/en.json` взглянуть?
У меня просто все подписи на месте.
Кстати, это еще кэш браузера/прокси может быть виноват...

**Comment by fishenebelny** [comment]
Файлик завтра добавлю.
Сейчас попробовал с телефона интеграцию добавить. Такую же ошибку выдает.

**Comment by IATkachenko** [comment]
Ошибка -- понятно (это я у себя тоже вижу и поправил). Меня беспокоит что на скрине поля не подписаны, а просто заголовок "настройки".

**Comment by IATkachenko** [comment]
Ага, воспроизвел отсутствие подписей локально -- кэш браузера точно замешан. Осталось понять чей )

**Comment by fishenebelny** [comment]
Проверил с телефона. Также не подписаны. А я на это внимание даже не обратил.

**Comment by IATkachenko** [comment]
;)
У меня эта проблема сейчас нормально воспроизводится. То что подписи были -- мой кэш поработал. Спасибо за участие.
