### ISSUE TITLE
Ночной режим для бризера

### ISSUE THREAD

**Issue by IATkachenko** [TionAPI/HA-tion#8]
Хочется добавить "ночной режим" в список предустановок.
Ночью хочется чтобы было попрохладнее (для лучшего сна) и бризер сильно не шумел.

Следовательно этом режиме бризер будет:
  * ограничивать максимальную скорость (2, если не задано в настройках);
  * снижать температуру нагревателя на N градусов (2, если не задано в настройках).

Для реализации, в принципе, все готово, но пока не доходят руки.
Можем обсудить, пока они доходят.

**Comment by fishenebelny** [comment]
На мой взгляд лучше  в интеграции делать именно управление. То есть какую-то карточку, которая позволит переключать скорости, включать или выключать обогрев, смотреть когда фильтры менять, какая температура и т.п.
А все автоматизации выносить в автоматизации на базе этой интеграции управления Тионом.

**Comment by IATkachenko** [comment]
Автоматизации не умеют запоминать состояния: вот, например, режим Турбо. Он выставляет 6ую скорость, а при его отмене возвращает ту, которая была. Автоматизациями это сделать очень сложно.

Более того, автоматизации нужно привязывать ко времени или состоянию внешнего сенсора и если есть автоматизация, например, на 4ую скорость по какому-то условию, то при наступлении этого условия ночью 4 скорость включится. Значит нужно это как-это дополнительно оборачивать.

Карточка, кстати, есть в HA, climate называется. И выглядит нормально
![Tion-card-2](https://user-images.githubusercontent.com/17473830/91158516-69733c80-e6cf-11ea-89b6-4def1250c618.png)
![Tion card](https://user-images.githubusercontent.com/17473830/91158532-7001b400-e6cf-11ea-9077-b58e3bfb6f15.png)

**Comment by fishenebelny** [comment]
На счет автоматизации понятно. Тогда  в мтдуле управления такие вещи действительно могут иметь место.

На счет карточки - вот эта большая шкала актуально, наверное, для термостата. А для проветривателя основной параметр - это скорость работы или кол-во поступающего воздуха. Если бы на дуге была не температура, а скорость - было бы более понятно, как мне кажется. Ну и прикрутить индикаицю в м3/час кроме самой скорости.

Чего мне не хватает в этой карточке - переключения заслонки. У нее же три режима:с улицы, смешанный и циркуляция.

Что меня в ней немного раздражает, так это то, что режим обогрева совмещен со статусом устройств. Тут два статуса в одном как бы.

**Comment by IATkachenko** [comment]
Карточки править, на данном этапе разработки не реально.
Сенсор и сервис для переключения режима заслонки в проекте (python-модуль это уже умеет).
На м3/ч -- feel free to open issue, как тут говорят. Сделать легко, много времени не займет.
Уходить из climate мы не можем, поскольку ближайший к нам fan не имеет сервисов работы с температурой и их придется изобретать самостоятельно, что очень не очень. Да и карточка для fan по мне так совсем не очень. Строить свой домен -- я пробовал в начале. Не пошло от слова совсем: оказалось что climate имеет почти все, что нам нужно и свой домен не окупает тех затрат, которые нужны на его создание.

А на счет "режим обогрева совмещен со статусом" это немного не так. У HA логика такая: есть тот режим в котором работает устройство и то, что оно делает сейчас (кстати, python-модуль применяет злобный хак чтобы понять что бризер делает сейчас и верить ему на все 100% нельзя). Те режим работы может быть "обогрев", а текущая деятельность -- "вентиляция", что и будет отображено на карточке.

По мне, после трех автоматизаций на скорость в зависимости от уровня co2, основной параметр -- температура, поскольку скорость -- та, которая нужна для поддержания приемлемого уровня co2 и руками в нее лазить не нужно от слова вообще.

Ну и еще пару слов про карточки. Есть https://github.com/finity69x2/fan-control-entity-row и fan карточка и, в принципе, ничего не стоит сделать fan-компонент и управлять бризером как fan. Я вам предлагаю попользоваться какое-то время как есть, понять что как и если окажется что управлять бризером как вентилятором нужно -- открыть issue на добавление возможности управления бризером как вентилятором.
