### ISSUE TITLE
Сенсор вентилятора не отражает выключенное состояние

### ISSUE THREAD

**Issue by fishenebelny** [TionAPI/HA-tion#82]
## Общая информация
  * **версия Home Assistant**: core-2022.6.6
  * **способ установки Home Assistant**:
    [ ] venv
    [x] Docker
    [ ] Home Assistant OS
 * **версия компонента**: 2.3.1
 * **модель бризера**: S3
 * **версия python-модуля**: 

[x] в момент проявления проблемы к бризеру никто не подключен
[x] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[x] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
Сенсор вентилятора не показывает выключенное состояние. То есть вентилятора не работает, а скорость показывает на момент выключения бризера. 

## Debug-log
```
Это не ошибка, а особенность.
```

## Как можно воспроизвети вашу проблему

1. Включить бризер
2. Выставить скорость бризера
3. Выключить скорость бризера
4. Сенсор вентилятора будет показывать что вентилятора вращается на скорости перед выключением.

**Comment by IATkachenko** [comment]
Исправлено в [v2.4.0](https://github.com/TionAPI/HA-tion/releases/tag/v2.4.0)
