### ISSUE TITLE
Home Assistant не отключается от бризера

### ISSUE THREAD

**Issue by IATkachenko** [TionAPI/HA-tion#83]
## Общая информация
  * **версия Home Assistant**: 2022.6
  * **способ установки Home Assistant**:
    [ ] venv
    [x] Docker
    [ ] Home Assistant OS
 * **версия компонента**: dev
 * **модель бризера**: S3

[x] в момент проявления проблемы к бризеру никто не подключен
[x] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[x] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
Периодически, при нормальной работе и отсутствии активного управления со стороны HA компонент остается подключенным к бризеру и не детектирует это состояние.

Возможно виноват BT/BTLE device tracker.
## Как можно воспроизвести вашу проблему
1. Запускаем HA, компонент считывает данные
2. Оставляем на некоторое время

**Comment by IATkachenko** [comment]
Если в момент такого "залипания" зайти в `bluetoothctl` (можно на хосте) будет видно, что висит соединение с бризером.
Дальше стандартное `bluetoothctl disconnect` и все снова работает.

ps. У меня на версии 2.2.x/2.3.x проблем не было до HA 2022.06 есть ощущение что там с асинхронностью что-то крутили.

**Comment by fishenebelny** [comment]
Понял. Если повторится, то проверю.

**Comment by IATkachenko** [comment]
@fishenebelny, если проблема актуальна -- попробуйте версию из ветки [i83](https://github.com/TionAPI/HA-tion/tree/i83)
Я там переделал механизм борьбы с параллельными запросами -- может помочь.

**Comment by fishenebelny** [comment]
Пока не повторялось, но в начале недели скорее всего обновлюсь.

**Comment by IATkachenko** [comment]
Я там сделал замечательный deadlock, при переключении предустановленных режимов.
Так что пока ветку удалю...

**Comment by fishenebelny** [comment]
Я правильно понял, что ничего обновлять пока нет необходимлсти?

**Comment by IATkachenko** [comment]
Да, пока обновлений/стабильного решения у меня нет.

**Comment by fishenebelny** [comment]
У меня пока проблем больше не возникало.
