### ISSUE TITLE
Миграция на bleak в HA 2022.07

### ISSUE THREAD

**Issue by IATkachenko** [TionAPI/HA-tion#87]
### Discussed in https://github.com/TionAPI/HA-tion/discussions/86

В 2022.07 Home Assistant, наконец, перешел на `bleak`.
Это значит что мы тоже можем откопать старые наработки и тоже перейти на `bleak`.

**Comment by ffrants** [comment]
Чтобы не создавать новый issue, спрошу тут.
Миграция на bleak поможет избавиться от недоступности вентилятора? 
Вот тут видно что он постоянно то доступен, то недоступен. Когда открываю Homekit чтобы поменять скорость, с 99% вероятностью, вентилятор одного из бризеров не доступен
![Uploading Снимок экрана 2022-07-08 в 15.05.59.png…]()

**Comment by IATkachenko** [comment]
> Чтобы не создавать новый issue, спрошу тут.

Это очень, очень, плохая практика. Не стоит экономить issue. Даже бумага не расходуется на них, а порядка и удобства это добавляет сильно.
Попробуйте поставить себя сегодняшнего, на место себя будущего, который столкнулся с проблемой недоступности вентилятора и ищет "что же могло случиться". Вы будущий НИКОГДА не найдет это обсуждение и потратит гораздо больше времени и сил, чем мог бы.

Недоступным он становится (внимательно не смотрел), если интеграция не может обновить состояние бризера. Так что ответ: "да и нет". Да, если пробелмы с доступностью из-за `bluepy` и всего этого (что, кстати, весьма вероятно: во время первых тестов `bleak`, несколько лет назад у меня вообще не было никаких пробелм с взаимодействием, в то время когда через `bluepy` бризер хоть редко, но становился недоступен) и нет, если там с чем-то еще пробелмы связаны и нужно разбираться.

**Comment by ffrants** [comment]
Понял, спасибо, больше так не буду ) 
Если после переезда на bleak проблема останется, создам отдельный issue
